'use strict';
const $=id=>document.getElementById(id);
const W=17,H=17,LEDGER='sushitan_login_bonus_v1',DUNGEON_SAVE='sushidungeon_meta_v1';
const DIRS=[[0,-1],[1,-1],[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1]];
const WEAPONS=[
 {name:'木の棒',type:'weapon',power:1,icon:'🪵',weight:28},{name:'川魚包丁',type:'weapon',power:3,icon:'🔪',weight:24},{name:'鉄の剣',type:'weapon',power:4,icon:'⚔️',weight:20},{name:'ロングソード',type:'weapon',power:5,icon:'🗡️',weight:15},{name:'銀の出刃包丁',type:'weapon',power:7,icon:'🔪',weight:8},{name:'古騎士の剣',type:'weapon',power:9,icon:'⚔️',weight:5}
];
const SHIELDS=[
 {name:'木の盾',type:'shield',power:1,icon:'🛡️',weight:30},{name:'樽ぶた',type:'shield',power:2,icon:'🛡️',weight:25},{name:'鉄の盾',type:'shield',power:4,icon:'🛡️',weight:20},{name:'堅いまな板',type:'shield',power:5,icon:'🪵',weight:15},{name:'騎士の盾',type:'shield',power:6,icon:'🛡️',weight:8},{name:'黒檀のまな板',type:'shield',power:8,icon:'🪵',weight:4}
];
const ACCESSORIES=[
 {name:'旅人のお守り',type:'accessory',effect:'regen',icon:'📿',weight:25,desc:'自然回復が少し速い'},{name:'食いしん坊の首飾り',type:'accessory',effect:'hunger',icon:'📿',weight:20,desc:'寿司の回復量+20'},{name:'剣士の腕輪',type:'accessory',effect:'attack',icon:'💍',weight:18,desc:'攻撃+2'},{name:'守りのピアス',type:'accessory',effect:'defense',icon:'✨',weight:18,desc:'防御+2'},{name:'幸運のペンダント',type:'accessory',effect:'luck',icon:'📿',weight:10,desc:'良いアイテムが出やすい'}
];
const CONSUMABLES=[
 {name:'マグロ',type:'sushi',value:35,icon:'🍣',weight:25},{name:'サーモン',type:'sushi',value:45,icon:'🍣',weight:18},{name:'大トロ',type:'sushi',value:70,icon:'🍣',weight:7},
 {name:'お茶',type:'tea',value:18,icon:'🍵',weight:24},{name:'濃いお茶',type:'tea',value:32,icon:'🍵',weight:10},{name:'玉露',type:'tea',value:50,icon:'🍵',weight:4},
 {name:'砥石',type:'whetstone',value:1,icon:'🪨',weight:8},{name:'補強材',type:'reinforce',value:1,icon:'🔩',weight:8},
 {name:'鑑定の巻物',type:'scroll',effect:'identify',icon:'📜',weight:6},{name:'地図の巻物',type:'scroll',effect:'map',icon:'📜',weight:6},{name:'転移の巻物',type:'scroll',effect:'warp',icon:'📜',weight:5},{name:'封印の巻物',type:'scroll',effect:'sleep',icon:'📜',weight:4}
];
const ENEMIES=[
 {name:'洞窟ネズミ',icon:'🐀',hp:6,atk:3,exp:2,min:1,max:3},
 {name:'緑小鬼',icon:'👺',hp:9,atk:4,exp:3,min:1,max:5},
 {name:'洞窟コウモリ',icon:'🦇',hp:7,atk:5,exp:3,min:2,max:6},
 {name:'骸骨兵',icon:'💀',hp:13,atk:6,exp:5,min:3,max:8},
 {name:'毒蜘蛛',icon:'🕷️',hp:11,atk:7,exp:5,min:4,max:9},
 {name:'オーク兵',icon:'👹',hp:18,atk:8,exp:7,min:5,max:10},
 {name:'石像兵',icon:'🗿',hp:23,atk:9,exp:9,min:7,max:10},
 {name:'洞窟トロル',icon:'🧌',hp:30,atk:11,exp:12,min:9,max:10}
];
let words=[];
let game=null,holdTimer=null,heldDir=null;
function rnd(n){return Math.floor(Math.random()*n)}
function key(x,y){return x+','+y}
function weighted(arr){const total=arr.reduce((s,x)=>s+(x.weight||1),0);let r=Math.random()*total;for(const x of arr){r-=x.weight||1;if(r<=0)return {...x};}return {...arr[arr.length-1]}}
function readAvatar(){try{const l=JSON.parse(localStorage.getItem(LEDGER)||'{}');return {...DEFAULT_AVATAR,...(l.gacha&&l.gacha.avatar||{})};}catch{return {...DEFAULT_AVATAR}}}
function readMeta(){try{return JSON.parse(localStorage.getItem(DUNGEON_SAVE)||'{}')}catch{return {}}}
function writeMeta(patch){const m={...readMeta(),...patch};localStorage.setItem(DUNGEON_SAVE,JSON.stringify(m));return m}
async function loadWords(){try{const r=await fetch('../data/words_master_v2_reviewed.json');const data=await r.json();words=data.filter(x=>x&&x.en&&x.jp).slice(0,1800);}catch{words=[{en:'follow',jp:'～の後に続く、～に従う'},{en:'consider',jp:'～を考慮する'},{en:'increase',jp:'増える、～を増やす'},{en:'expect',jp:'～を予期する'}]}}
function startGame(){game={floor:1,level:1,exp:0,nextExp:7,hp:20,maxHp:20,hunger:100,maxHunger:100,turn:0,weapon:null,shield:null,accessory:null,inventory:[],foundGear:[],logs:[],dead:false,mapReveal:false};generateFloor();log('冒険を開始した。10Fを目指せ。');render()}
function carveRoom(grid,x,y,w,h){for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)grid[yy][xx]=1}
function corridor(grid,a,b){let x=a.x,y=a.y;while(x!==b.x){grid[y][x]=1;x+=Math.sign(b.x-x)}while(y!==b.y){grid[y][x]=1;y+=Math.sign(b.y-y)}grid[y][x]=1}
function generateFloor(){const grid=Array.from({length:H},()=>Array(W).fill(0)),rooms=[];for(let tries=0;tries<35&&rooms.length<6;tries++){const w=3+rnd(3),h=3+rnd(3),x=1+rnd(W-w-2),y=1+rnd(H-h-2);if(rooms.some(r=>x<r.x+r.w+1&&x+w+1>r.x&&y<r.y+r.h+1&&y+h+1>r.y))continue;const room={x,y,w,h,cx:x+Math.floor(w/2),cy:y+Math.floor(h/2)};carveRoom(grid,x,y,w,h);if(rooms.length)corridor(grid,{x:rooms.at(-1).cx,y:rooms.at(-1).cy},{x:room.cx,y:room.cy});rooms.push(room)}if(rooms.length<2){carveRoom(grid,1,1,5,5);carveRoom(grid,7,7,5,5);corridor(grid,{x:3,y:3},{x:9,y:9});rooms.push({cx:3,cy:3},{cx:9,cy:9})}
 game.grid=grid;game.player={x:rooms[0].cx,y:rooms[0].cy};game.exit={x:rooms.at(-1).cx,y:rooms.at(-1).cy};game.enemies=[];game.items=[];game.chest=null;game.mapReveal=false;
 const open=[];for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++)if(grid[y][x]&&key(x,y)!==key(game.player.x,game.player.y)&&key(x,y)!==key(game.exit.x,game.exit.y))open.push({x,y});
 const take=()=>open.splice(rnd(open.length),1)[0];
 const enemyCount=3+Math.floor(game.floor*.65);for(let i=0;i<enemyCount&&open.length;i++){const p=take(),pool=ENEMIES.filter(e=>game.floor>=e.min&&game.floor<=e.max),base=pool[rnd(pool.length)];game.enemies.push({...base,x:p.x,y:p.y,hp:base.hp+Math.floor(game.floor/3),maxHp:base.hp+Math.floor(game.floor/3),asleep:false})}
 const itemCount=2+rnd(3);for(let i=0;i<itemCount&&open.length;i++){const p=take();game.items.push({...randomItem(false),x:p.x,y:p.y})}
 if(open.length){const p=take();game.chest={x:p.x,y:p.y,opened:false}}
 msg(`${game.floor}F。階段を探そう。`)}
function randomItem(good){const luck=game&&game.accessory?.effect==='luck';const roll=Math.random();if(good||luck&&Math.random()<.25){if(roll<.42)return weighted(WEAPONS.slice(2));if(roll<.78)return weighted(SHIELDS.slice(2));if(roll<.92)return weighted(ACCESSORIES);return weighted(CONSUMABLES)}if(roll<.25)return weighted(WEAPONS);if(roll<.47)return weighted(SHIELDS);if(roll<.58)return weighted(ACCESSORIES);return weighted(CONSUMABLES)}
function occupied(x,y){return game.enemies.some(e=>e.hp>0&&e.x===x&&e.y===y)}
function move(dx,dy){if(!game||game.dead||$('wordDialog').open||$('inventoryDialog').open)return;const nx=game.player.x+dx,ny=game.player.y+dy;if(nx<0||ny<0||nx>=W||ny>=H||!game.grid[ny][nx])return;const enemy=game.enemies.find(e=>e.hp>0&&e.x===nx&&e.y===ny);if(enemy){attack(enemy);endTurn();return}if(dx&&dy){if(!game.grid[game.player.y][nx]&&!game.grid[ny][game.player.x])return}game.player={x:nx,y:ny};pickup();if(game.chest&&!game.chest.open&&nx===game.chest.x&&ny===game.chest.y){game.chest.open=true;openWordChest()}if(nx===game.exit.x&&ny===game.exit.y){descend();return}endTurn()}
function attack(e){const atk=2+game.level+(game.weapon?.power||0)+(game.weapon?.plus||0)+(game.accessory?.effect==='attack'?2:0),dmg=Math.max(1,atk-1+rnd(4));e.hp-=dmg;msg(`${e.name}に${dmg}ダメージ。`);if(e.hp<=0){game.exp+=e.exp;log(`${e.name}を倒した。`);while(game.exp>=game.nextExp){game.exp-=game.nextExp;game.level++;game.nextExp=Math.floor(game.nextExp*1.45)+3;game.maxHp+=4;game.hp=game.maxHp;msg(`レベル${game.level}！ HP全回復。`);log(`Lv ${game.level}になった。`)}}}
function enemyTurn(){for(const e of game.enemies){if(e.hp<=0)continue;if(e.asleep){if(Math.random()<.18)e.asleep=false;continue}const dx=game.player.x-e.x,dy=game.player.y-e.y;if(Math.max(Math.abs(dx),Math.abs(dy))<=1){const def=(game.shield?.power||0)+(game.shield?.plus||0)+(game.accessory?.effect==='defense'?2:0),dmg=Math.max(1,e.atk+Math.floor(game.floor/4)-Math.floor(def*.55)+rnd(3)-1);game.hp-=dmg;msg(`${e.name}の攻撃！ ${dmg}ダメージ。`);if(game.hp<=0){die(e.name);return}continue}if(Math.abs(dx)+Math.abs(dy)<8){const sx=Math.sign(dx),sy=Math.sign(dy),tries=[[sx,sy],[sx,0],[0,sy]].sort(()=>Math.random()-.5);for(const [mx,my] of tries){const nx=e.x+mx,ny=e.y+my;if(game.grid[ny]?.[nx]&&!occupied(nx,ny)&&!(nx===game.player.x&&ny===game.player.y)){e.x=nx;e.y=ny;break}}}else if(Math.random()<.35){const [mx,my]=DIRS[rnd(DIRS.length)],nx=e.x+mx,ny=e.y+my;if(game.grid[ny]?.[nx]&&!occupied(nx,ny)){e.x=nx;e.y=ny}}}}
function endTurn(){if(game.dead)return;game.turn++;if(game.turn%8===0)game.hunger=Math.max(0,game.hunger-1);if(game.hunger>0&&game.turn%(game.accessory?.effect==='regen'?3:5)===0)game.hp=Math.min(game.maxHp,game.hp+1);if(game.hunger===0&&game.turn%3===0){game.hp--;if(game.hp<=0){die('空腹');return}}enemyTurn();render()}
function pickup(){const i=game.items.findIndex(it=>it.x===game.player.x&&it.y===game.player.y);if(i<0)return;const item=game.items.splice(i,1)[0];delete item.x;delete item.y;game.inventory.push(item);if(['weapon','shield','accessory'].includes(item.type))game.foundGear.push({...item});msg(`${item.icon} ${item.name}を拾った。`);log(`${item.name}を拾った。`)}
function descend(){if(game.floor>=10){reachTen();return}game.floor++;generateFloor();log(`${game.floor}Fへ降りた。`);render()}
function openWordChest(){if(!words.length)return;const q=words[rnd(words.length)],wrong=[];while(wrong.length<3){const w=words[rnd(words.length)];if(w.jp!==q.jp&&!wrong.includes(w.jp))wrong.push(w.jp)}const choices=[q.jp,...wrong].sort(()=>Math.random()-.5);$('wordPrompt').textContent=q.en;$('wordChoices').replaceChildren();for(const c of choices){const b=document.createElement('button');b.type='button';b.textContent=c;b.onclick=()=>{[...$('wordChoices').children].forEach(x=>x.disabled=true);if(c===q.jp){const prize=randomItem(true);game.inventory.push(prize);if(['weapon','shield','accessory'].includes(prize.type))game.foundGear.push({...prize});msg(`正解！ ${prize.icon} ${prize.name}を手に入れた。`);log(`英単語宝箱「${q.en}」正解 → ${prize.name}`)}else{msg(`不正解。「${q.en}」＝ ${q.jp}`);log(`英単語宝箱「${q.en}」不正解`)}setTimeout(()=>{$('wordDialog').close();endTurn()},650)};$('wordChoices').append(b)}$('wordDialog').showModal()}
function useItem(index){const item=game.inventory[index];if(!item)return;if(item.type==='weapon'){game.weapon=item;msg(`${item.name}を装備した。`)}else if(item.type==='shield'){game.shield=item;msg(`${item.name}を装備した。`)}else if(item.type==='accessory'){game.accessory=item;msg(`${item.name}を装備した。`)}else if(item.type==='tea'){game.hp=Math.min(game.maxHp,game.hp+item.value);game.inventory.splice(index,1);msg(`${item.name}を飲んだ。HP回復。`)}else if(item.type==='sushi'){const bonus=game.accessory?.effect==='hunger'?20:0;game.hunger=Math.min(game.maxHunger,game.hunger+item.value+bonus);game.inventory.splice(index,1);msg(`${item.name}を食べた。満腹度回復。`)}else if(item.type==='whetstone'){if(game.weapon){game.weapon.plus=(game.weapon.plus||0)+1;game.inventory.splice(index,1);msg(`${game.weapon.name}を+${game.weapon.plus}に鍛えた。`)}else{msg('強化する武器を装備していない。');return}}else if(item.type==='reinforce'){if(game.shield){game.shield.plus=(game.shield.plus||0)+1;game.inventory.splice(index,1);msg(`${game.shield.name}を+${game.shield.plus}に補強した。`)}else{msg('強化する盾を装備していない。');return}}else if(item.type==='scroll'){if(item.effect==='map'){game.mapReveal=true;msg('地図が頭に浮かんだ。')}if(item.effect==='warp'){const spots=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(game.grid[y][x]&&!occupied(x,y))spots.push({x,y});game.player=spots[rnd(spots.length)];msg('空間がねじれた！')}if(item.effect==='sleep'){game.enemies.forEach(e=>e.asleep=true);msg('敵たちは静まり返った。')}if(item.effect==='identify')msg('この試作版では、すべての道具を識別できた。');game.inventory.splice(index,1)}$('inventoryDialog').close();endTurn();render()}
function renderInventory(){const list=$('inventoryList');list.replaceChildren();if(!game.inventory.length){list.innerHTML='<p class="empty">何も持っていない。</p>';return}game.inventory.forEach((it,i)=>{const b=document.createElement('button');b.type='button';const plus=it.plus?` +${it.plus}`:'';b.innerHTML=`<span>${it.icon} ${it.name}${plus}</span><small>${it.type==='weapon'?'攻 '+it.power:it.type==='shield'?'防 '+it.power:it.desc||'使う / 装備'}</small>`;b.onclick=()=>useItem(i);list.append(b)})}
function reachTen(){const meta=readMeta(),best=Math.max(meta.bestFloor||0,10);writeMeta({bestFloor:best,runs:(meta.runs||0)+1});$('keepList').replaceChildren();const unique=game.foundGear.filter((x,i,a)=>a.findIndex(y=>y.name===x.name&&y.type===x.type)===i);if(!unique.length)$('keepList').innerHTML='<p class="empty">持ち帰れる装備がない。</p>';for(const it of unique){const b=document.createElement('button');b.type='button';b.innerHTML=`<span>${it.icon} ${it.name}</span><small>アバタートロフィーとして保存</small>`;b.onclick=()=>{const m=readMeta(),t=[...(m.trophies||[])];t.push({...it,fromFloor:10,obtainedAt:Date.now()});writeMeta({trophies:t,bestFloor:10,runs:m.runs||0});$('keepDialog').close();finishClear(it.name)};$('keepList').append(b)}$('keepDialog').showModal()}
function finishClear(name){game.dead=true;$('gameOverTitle').textContent='10F到達！';$('gameOverText').textContent=(name?`${name}を持ち帰った。`:'今回は装備を持ち帰らなかった。')+' 試作ダンジョン制覇。次の冒険も1Fから。';$('gameOverDialog').showModal()}
function die(cause){game.dead=true;const m=readMeta(),best=Math.max(m.bestFloor||0,game.floor);writeMeta({bestFloor:best,runs:(m.runs||0)+1});$('gameOverTitle').textContent='力尽きた…';$('gameOverText').textContent=`${game.floor}F / Lv ${game.level}。原因：${cause}。装備と道具は失われた。最高到達 ${best}F。`;$('gameOverDialog').showModal()}
function log(t){game.logs.unshift(`[${game.floor}F] ${t}`);game.logs=game.logs.slice(0,80)}
function msg(t){$('message').textContent=t;const f=$('floatMsg');f.textContent=t;f.hidden=false;clearTimeout(msg.t);msg.t=setTimeout(()=>f.hidden=true,850)}
function render(){if(!game)return;$('floorLabel').textContent=game.floor+'F';$('levelLabel').textContent='Lv '+game.level;$('hpLabel').textContent=`HP ${Math.max(0,game.hp)}/${game.maxHp}`;$('hungerLabel').textContent=`🍣 ${game.hunger}/${game.maxHunger}`;$('hpBar').style.width=Math.max(0,game.hp/game.maxHp*100)+'%';$('hungerBar').style.width=game.hunger/game.maxHunger*100+'%';$('weaponLabel').textContent='⚔ '+(game.weapon?game.weapon.name+(game.weapon.plus?' +'+game.weapon.plus:''):'素手');$('shieldLabel').textContent='🛡 '+(game.shield?game.shield.name+(game.shield.plus?' +'+game.shield.plus:''):'なし');$('accLabel').textContent='✨ '+(game.accessory?.name||'なし');$('invCount').textContent=game.inventory.length;
 const board=$('board');board.style.gridTemplateColumns=`repeat(${W},1fr)`;board.style.gridTemplateRows=`repeat(${H},1fr)`;board.replaceChildren();const avatar=readAvatar();for(let y=0;y<H;y++)for(let x=0;x<W;x++){const c=document.createElement('div');c.className='cell '+(game.grid[y][x]?'floor':'wall');if(game.grid[y][x]&&x===game.exit.x&&y===game.exit.y)c.classList.add('exit');const item=game.items.find(i=>i.x===x&&i.y===y);if(item)c.insertAdjacentHTML('beforeend',`<span class="entity item">${item.icon}</span>`);if(game.chest&&!game.chest.open&&game.chest.x===x&&game.chest.y===y)c.insertAdjacentHTML('beforeend','<span class="entity treasure">🎁</span>');const e=game.enemies.find(e=>e.hp>0&&e.x===x&&e.y===y);if(e)c.insertAdjacentHTML('beforeend',`<span class="entity enemy" title="${e.name}">${e.icon}</span>`);if(game.player.x===x&&game.player.y===y){const p=document.createElement('span');p.className='entity player';p.innerHTML=avatarSVG(avatar);c.append(p)}board.append(c)}}
function bindControls(){document.querySelectorAll('[data-dir]').forEach(b=>{const d=b.dataset.dir.split(',').map(Number);const fire=()=>move(d[0],d[1]);b.addEventListener('pointerdown',e=>{e.preventDefault();fire();heldDir=d;clearTimeout(holdTimer);holdTimer=setTimeout(()=>{holdTimer=setInterval(()=>{if(game&&!game.dead&&!enemyAdjacent())fire()},130)},350)});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>{clearTimeout(holdTimer);clearInterval(holdTimer);heldDir=null}))});$('waitBtn').onclick=()=>endTurn();$('inventoryBtn').onclick=()=>{renderInventory();$('inventoryDialog').showModal()};$('logBtn').onclick=()=>{$('logList').innerHTML=game.logs.map(x=>`<p>${x}</p>`).join('');$('logDialog').showModal()};$('retryBtn').onclick=()=>{setTimeout(startGame,0)};$('keepNone').onclick=()=>setTimeout(()=>finishClear(null),0);
 let sx=0,sy=0,active=false;$('boardWrap').addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;active=true});$('boardWrap').addEventListener('pointerup',e=>{if(!active)return;active=false;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.hypot(dx,dy)<22)return;move(Math.abs(dx)>18?Math.sign(dx):0,Math.abs(dy)>18?Math.sign(dy):0)})}
function enemyAdjacent(){return game.enemies.some(e=>e.hp>0&&Math.max(Math.abs(e.x-game.player.x),Math.abs(e.y-game.player.y))<=1)}
(async()=>{await loadWords();bindControls();startGame()})();