// 100 classical-music questions for Sushi Quiz.
// Loaded after the other extension banks and merged without exact duplicates.
const SUSHI_QUIZ_CLASSICAL_MUSIC = [
{"cat":"Music","q":"Who composed Jupiter from The Planets?","choices":["Gustav Holst","Edward Elgar","Ralph Vaughan Williams","Benjamin Britten"],"ans":0,"exp":"Gustav Holst composed The Planets; Jupiter is its fourth movement."},
{"cat":"Music","q":"Who composed The Carnival of the Animals?","choices":["Claude Debussy","Camille Saint-Saens","Maurice Ravel","Georges Bizet"],"ans":1,"exp":"Camille Saint-Saens composed The Carnival of the Animals."},
{"cat":"Music","q":"Who composed Danse macabre?","choices":["Hector Berlioz","Gabriel Faure","Camille Saint-Saens","Cesar Franck"],"ans":2,"exp":"Camille Saint-Saens composed the symphonic poem Danse macabre."},
{"cat":"Music","q":"In traditional Japanese music education, who is often called the Father of Music?","choices":["Johann Sebastian Bach","Mozart","Beethoven","Haydn"],"ans":0,"exp":"In Japan, Bach has traditionally been nicknamed the Father of Music; this is not a universal formal title."},
{"cat":"Music","q":"In traditional Japanese music education, who is sometimes called the Mother of Music?","choices":["Vivaldi","Handel","Schubert","Chopin"],"ans":1,"exp":"In Japan, Handel has sometimes been nicknamed the Mother of Music; this is a Japanese educational convention rather than a universal title."},
{"cat":"Music","q":"Who composed Eine kleine Nachtmusik?","choices":["Haydn","Mozart","Schubert","Beethoven"],"ans":1,"exp":"Wolfgang Amadeus Mozart composed Eine kleine Nachtmusik."},
{"cat":"Music","q":"Who composed the Fifth Symphony famous for its short-short-short-long opening?","choices":["Brahms","Mahler","Beethoven","Bruckner"],"ans":2,"exp":"Beethoven's Symphony No. 5 opens with the famous four-note motif."},
{"cat":"Music","q":"Who composed The Four Seasons?","choices":["Vivaldi","Corelli","Handel","Bach"],"ans":0,"exp":"Antonio Vivaldi composed the four violin concertos known as The Four Seasons."},
{"cat":"Music","q":"Who composed the New World Symphony?","choices":["Smetana","Dvorak","Janacek","Sibelius"],"ans":1,"exp":"Antonin Dvorak composed Symphony No. 9, From the New World."},
{"cat":"Music","q":"Who composed Bolero?","choices":["Debussy","Ravel","Satie","Faure"],"ans":1,"exp":"Maurice Ravel composed Bolero."},
{"cat":"Music","q":"Who composed Pictures at an Exhibition?","choices":["Rimsky-Korsakov","Borodin","Mussorgsky","Tchaikovsky"],"ans":2,"exp":"Modest Mussorgsky originally composed Pictures at an Exhibition for piano."},
{"cat":"Music","q":"Who composed The Blue Danube?","choices":["Johann Strauss II","Johann Strauss I","Franz Lehar","Franz Schubert"],"ans":0,"exp":"Johann Strauss II composed the waltz The Blue Danube."},
{"cat":"Music","q":"Who composed the opera Carmen?","choices":["Verdi","Bizet","Puccini","Rossini"],"ans":1,"exp":"Georges Bizet composed Carmen."},
{"cat":"Music","q":"Who composed the opera The Magic Flute?","choices":["Mozart","Wagner","Gluck","Handel"],"ans":0,"exp":"Mozart composed The Magic Flute near the end of his life."},
{"cat":"Music","q":"Who composed the ballet Swan Lake?","choices":["Prokofiev","Stravinsky","Tchaikovsky","Rimsky-Korsakov"],"ans":2,"exp":"Pyotr Ilyich Tchaikovsky composed Swan Lake."},
{"cat":"Music","q":"Who composed the ballet The Nutcracker?","choices":["Tchaikovsky","Mussorgsky","Borodin","Rachmaninoff"],"ans":0,"exp":"Tchaikovsky composed The Nutcracker."},
{"cat":"Music","q":"Who composed The Rite of Spring?","choices":["Stravinsky","Ravel","Bartok","Prokofiev"],"ans":0,"exp":"Igor Stravinsky composed The Rite of Spring."},
{"cat":"Music","q":"Who composed Clair de lune?","choices":["Ravel","Debussy","Satie","Chopin"],"ans":1,"exp":"Claude Debussy composed Clair de lune as part of Suite bergamasque."},
{"cat":"Music","q":"Who composed Gymnopedie No. 1?","choices":["Faure","Satie","Debussy","Ravel"],"ans":1,"exp":"Erik Satie composed the Gymnopedies."},
{"cat":"Music","q":"Who composed Finlandia?","choices":["Grieg","Sibelius","Nielsen","Dvorak"],"ans":1,"exp":"Jean Sibelius composed Finlandia."},
{"cat":"Music","q":"Who composed Peer Gynt, including Morning Mood and In the Hall of the Mountain King?","choices":["Grieg","Sibelius","Nielsen","Mendelssohn"],"ans":0,"exp":"Edvard Grieg wrote the incidental music for Peer Gynt."},
{"cat":"Music","q":"Who composed The Moldau, also known as Vltava?","choices":["Dvorak","Smetana","Liszt","Brahms"],"ans":1,"exp":"Bedrich Smetana composed Vltava, commonly called The Moldau in English."},
{"cat":"Music","q":"Who composed Hungarian Rhapsody No. 2?","choices":["Liszt","Brahms","Bartok","Kodaly"],"ans":0,"exp":"Franz Liszt composed Hungarian Rhapsody No. 2."},
{"cat":"Music","q":"Who composed the Minute Waltz?","choices":["Schumann","Chopin","Liszt","Schubert"],"ans":1,"exp":"Frederic Chopin composed the Waltz in D-flat major commonly nicknamed the Minute Waltz."},
{"cat":"Music","q":"Who composed the Moonlight Sonata?","choices":["Beethoven","Mozart","Haydn","Schubert"],"ans":0,"exp":"Beethoven composed Piano Sonata No. 14, later nicknamed the Moonlight Sonata."},
{"cat":"Music","q":"Who composed Fur Elise?","choices":["Schubert","Beethoven","Brahms","Schumann"],"ans":1,"exp":"Fur Elise is one of Beethoven's best-known piano pieces."},
{"cat":"Music","q":"Who composed the Unfinished Symphony?","choices":["Schumann","Schubert","Bruckner","Mahler"],"ans":1,"exp":"Franz Schubert's Symphony No. 8 is commonly called the Unfinished Symphony."},
{"cat":"Music","q":"Who composed the Surprise Symphony?","choices":["Haydn","Mozart","Beethoven","Schubert"],"ans":0,"exp":"Joseph Haydn's Symphony No. 94 is nicknamed the Surprise Symphony."},
{"cat":"Music","q":"Who composed the Pastoral Symphony, Symphony No. 6?","choices":["Beethoven","Berlioz","Brahms","Mahler"],"ans":0,"exp":"Beethoven's Symphony No. 6 is known as the Pastoral Symphony."},
{"cat":"Music","q":"Who composed Messiah?","choices":["Bach","Handel","Vivaldi","Purcell"],"ans":1,"exp":"George Frideric Handel composed the oratorio Messiah."},
{"cat":"Music","q":"Who composed the Brandenburg Concertos?","choices":["Handel","Bach","Telemann","Vivaldi"],"ans":1,"exp":"Johann Sebastian Bach composed the six Brandenburg Concertos."},
{"cat":"Music","q":"Who composed Toccata and Fugue in D minor, traditionally attributed to him?","choices":["Bach","Handel","Pachelbel","Buxtehude"],"ans":0,"exp":"Toccata and Fugue in D minor is traditionally attributed to Johann Sebastian Bach, though its authorship has been debated."},
{"cat":"Music","q":"Who composed Canon in D?","choices":["Pachelbel","Bach","Vivaldi","Corelli"],"ans":0,"exp":"Johann Pachelbel composed the famous Canon in D."},
{"cat":"Music","q":"Who composed Water Music?","choices":["Handel","Bach","Purcell","Vivaldi"],"ans":0,"exp":"Handel composed the orchestral suites known as Water Music."},
{"cat":"Music","q":"Who composed Music for the Royal Fireworks?","choices":["Purcell","Handel","Bach","Telemann"],"ans":1,"exp":"Handel composed Music for the Royal Fireworks."},
{"cat":"Music","q":"Who composed Requiem in D minor, K. 626?","choices":["Mozart","Verdi","Faure","Berlioz"],"ans":0,"exp":"Mozart's Requiem in D minor was left unfinished at his death."},
{"cat":"Music","q":"Who composed the German Requiem?","choices":["Brahms","Schumann","Mendelssohn","Wagner"],"ans":0,"exp":"Johannes Brahms composed A German Requiem."},
{"cat":"Music","q":"Who composed the opera La Traviata?","choices":["Puccini","Verdi","Rossini","Donizetti"],"ans":1,"exp":"Giuseppe Verdi composed La Traviata."},
{"cat":"Music","q":"Who composed the opera Aida?","choices":["Verdi","Puccini","Bizet","Wagner"],"ans":0,"exp":"Giuseppe Verdi composed Aida."},
{"cat":"Music","q":"Who composed the opera La Boheme?","choices":["Verdi","Puccini","Mascagni","Rossini"],"ans":1,"exp":"Giacomo Puccini composed La Boheme."},
{"cat":"Music","q":"Who composed the opera Madama Butterfly?","choices":["Puccini","Verdi","Bellini","Donizetti"],"ans":0,"exp":"Giacomo Puccini composed Madama Butterfly."},
{"cat":"Music","q":"Who composed Ride of the Valkyries?","choices":["Wagner","Mahler","Strauss","Bruckner"],"ans":0,"exp":"Richard Wagner composed Ride of the Valkyries as part of Die Walkure."},
{"cat":"Music","q":"Who composed Also sprach Zarathustra?","choices":["Richard Strauss","Johann Strauss II","Wagner","Mahler"],"ans":0,"exp":"Richard Strauss composed the tone poem Also sprach Zarathustra."},
{"cat":"Music","q":"Who composed The Young Person's Guide to the Orchestra?","choices":["Holst","Britten","Elgar","Vaughan Williams"],"ans":1,"exp":"Benjamin Britten composed The Young Person's Guide to the Orchestra."},
{"cat":"Music","q":"Who composed the Enigma Variations?","choices":["Elgar","Holst","Britten","Delius"],"ans":0,"exp":"Edward Elgar composed the Enigma Variations."},
{"cat":"Music","q":"Who composed Pomp and Circumstance March No. 1?","choices":["Elgar","Holst","Sousa","Walton"],"ans":0,"exp":"Edward Elgar composed the Pomp and Circumstance marches."},
{"cat":"Music","q":"Who composed Rhapsody in Blue?","choices":["Gershwin","Bernstein","Copland","Barber"],"ans":0,"exp":"George Gershwin composed Rhapsody in Blue."},
{"cat":"Music","q":"Who composed Appalachian Spring?","choices":["Copland","Gershwin","Bernstein","Ives"],"ans":0,"exp":"Aaron Copland composed Appalachian Spring."},
{"cat":"Music","q":"Who composed the ballet Romeo and Juliet?","choices":["Prokofiev","Stravinsky","Khachaturian","Shostakovich"],"ans":0,"exp":"Sergei Prokofiev composed the ballet Romeo and Juliet."},
{"cat":"Music","q":"Who composed Sabre Dance?","choices":["Khachaturian","Prokofiev","Shostakovich","Borodin"],"ans":0,"exp":"Aram Khachaturian composed Sabre Dance as part of the ballet Gayane."},
{"cat":"Music","q":"Who composed Scheherazade?","choices":["Borodin","Rimsky-Korsakov","Mussorgsky","Tchaikovsky"],"ans":1,"exp":"Nikolai Rimsky-Korsakov composed the symphonic suite Scheherazade."},
{"cat":"Music","q":"Who composed In the Steppes of Central Asia?","choices":["Borodin","Mussorgsky","Balakirev","Rimsky-Korsakov"],"ans":0,"exp":"Alexander Borodin composed the symphonic poem In the Steppes of Central Asia."},
{"cat":"Music","q":"Who composed The Sorcerer's Apprentice?","choices":["Dukas","Saint-Saens","Berlioz","Bizet"],"ans":0,"exp":"Paul Dukas composed the symphonic poem The Sorcerer's Apprentice."},
{"cat":"Music","q":"Who composed Symphonie fantastique?","choices":["Berlioz","Franck","Bizet","Faure"],"ans":0,"exp":"Hector Berlioz composed Symphonie fantastique."},
{"cat":"Music","q":"Who composed Pavane, Op. 50?","choices":["Faure","Ravel","Debussy","Satie"],"ans":0,"exp":"Gabriel Faure composed the well-known Pavane, Op. 50."},
{"cat":"Music","q":"Who composed the opera The Barber of Seville?","choices":["Rossini","Verdi","Puccini","Bellini"],"ans":0,"exp":"Gioachino Rossini composed The Barber of Seville."},
{"cat":"Music","q":"Who composed the William Tell Overture?","choices":["Rossini","Verdi","Donizetti","Bellini"],"ans":0,"exp":"Rossini composed the overture to his opera William Tell."},
{"cat":"Music","q":"Which composer became deaf later in life but continued composing major works?","choices":["Beethoven","Mozart","Chopin","Vivaldi"],"ans":0,"exp":"Beethoven experienced severe hearing loss and continued to compose major works."},
{"cat":"Music","q":"Which composer was a famous virtuoso violinist and wrote 24 Caprices for Solo Violin?","choices":["Paganini","Liszt","Sarasate","Vieuxtemps"],"ans":0,"exp":"Niccolo Paganini was a legendary violin virtuoso and composed the 24 Caprices."},
{"cat":"Music","q":"Which composer was a celebrated piano virtuoso and developed the symphonic poem?","choices":["Liszt","Chopin","Brahms","Schumann"],"ans":0,"exp":"Franz Liszt was a celebrated pianist and a major developer of the symphonic poem."},
{"cat":"Music","q":"Which composer wrote mainly for the piano and was born in Poland?","choices":["Chopin","Liszt","Debussy","Schubert"],"ans":0,"exp":"Frederic Chopin was born in Poland and is especially associated with piano music."},
{"cat":"Music","q":"Which composer wrote the opera cycle Der Ring des Nibelungen?","choices":["Wagner","Verdi","Strauss","Mahler"],"ans":0,"exp":"Richard Wagner composed the four-opera Ring cycle."},
{"cat":"Music","q":"Which composer wrote nine numbered symphonies and the song cycle Das Lied von der Erde?","choices":["Mahler","Bruckner","Brahms","Strauss"],"ans":0,"exp":"Gustav Mahler completed nine numbered symphonies and composed Das Lied von der Erde."},
{"cat":"Music","q":"Which composer wrote four symphonies and the Academic Festival Overture?","choices":["Brahms","Schumann","Mendelssohn","Bruckner"],"ans":0,"exp":"Johannes Brahms composed four symphonies and the Academic Festival Overture."},
{"cat":"Music","q":"Which composer wrote the Wedding March often heard at weddings?","choices":["Mendelssohn","Wagner","Schumann","Brahms"],"ans":0,"exp":"Felix Mendelssohn's Wedding March comes from his music for A Midsummer Night's Dream."},
{"cat":"Music","q":"Which composer wrote the Trout Quintet?","choices":["Schubert","Schumann","Brahms","Haydn"],"ans":0,"exp":"Franz Schubert composed the Piano Quintet commonly called the Trout Quintet."},
{"cat":"Music","q":"Which composer wrote Kinderszenen, including Traumerei?","choices":["Schumann","Schubert","Brahms","Chopin"],"ans":0,"exp":"Robert Schumann composed Kinderszenen, whose best-known movement is Traumerei."},
{"cat":"Music","q":"Which composer wrote the opera Hansel and Gretel?","choices":["Humperdinck","Wagner","Weber","Strauss"],"ans":0,"exp":"Engelbert Humperdinck composed the opera Hansel and Gretel."},
{"cat":"Music","q":"Which composer wrote the opera Der Freischutz?","choices":["Weber","Wagner","Mozart","Gluck"],"ans":0,"exp":"Carl Maria von Weber composed Der Freischutz."},
{"cat":"Music","q":"Which composer wrote the ballet The Firebird?","choices":["Stravinsky","Prokofiev","Tchaikovsky","Ravel"],"ans":0,"exp":"Igor Stravinsky composed The Firebird for the Ballets Russes."},
{"cat":"Music","q":"Which composer wrote the ballet Daphnis et Chloe?","choices":["Ravel","Debussy","Stravinsky","Faure"],"ans":0,"exp":"Maurice Ravel composed the ballet Daphnis et Chloe."},
{"cat":"Music","q":"Which composer wrote Prelude to the Afternoon of a Faun?","choices":["Debussy","Ravel","Satie","Faure"],"ans":0,"exp":"Claude Debussy composed Prelude to the Afternoon of a Faun."},
{"cat":"Music","q":"Which composer wrote the opera Prince Igor?","choices":["Borodin","Mussorgsky","Rimsky-Korsakov","Tchaikovsky"],"ans":0,"exp":"Alexander Borodin composed Prince Igor, though it was unfinished at his death."},
{"cat":"Music","q":"Which composer wrote Night on Bald Mountain?","choices":["Mussorgsky","Borodin","Rimsky-Korsakov","Balakirev"],"ans":0,"exp":"Modest Mussorgsky composed Night on Bald Mountain."},
{"cat":"Music","q":"Which composer wrote the 1812 Overture?","choices":["Tchaikovsky","Borodin","Rimsky-Korsakov","Glinka"],"ans":0,"exp":"Tchaikovsky composed the 1812 Overture."},
{"cat":"Music","q":"Which composer wrote the overture The Hebrides, also called Fingal's Cave?","choices":["Mendelssohn","Schumann","Brahms","Weber"],"ans":0,"exp":"Felix Mendelssohn composed The Hebrides overture."},
{"cat":"Music","q":"Which composer wrote The Lark Ascending?","choices":["Vaughan Williams","Elgar","Holst","Britten"],"ans":0,"exp":"Ralph Vaughan Williams composed The Lark Ascending."},
{"cat":"Music","q":"Which composer wrote Peter Grimes?","choices":["Britten","Elgar","Holst","Vaughan Williams"],"ans":0,"exp":"Benjamin Britten composed the opera Peter Grimes."},
{"cat":"Music","q":"Which composer wrote Adagio for Strings?","choices":["Samuel Barber","Aaron Copland","George Gershwin","Charles Ives"],"ans":0,"exp":"Samuel Barber composed Adagio for Strings."},
{"cat":"Music","q":"Which composer wrote West Side Story?","choices":["Leonard Bernstein","George Gershwin","Aaron Copland","Stephen Sondheim"],"ans":0,"exp":"Leonard Bernstein composed the music for West Side Story; Stephen Sondheim wrote the lyrics."},
{"cat":"Music","q":"Which composer wrote the opera Porgy and Bess?","choices":["Gershwin","Bernstein","Copland","Barber"],"ans":0,"exp":"George Gershwin composed Porgy and Bess."},
{"cat":"Music","q":"Which period came first in Western classical music history?","choices":["Baroque","Classical","Romantic","Modern"],"ans":0,"exp":"The Baroque period preceded the Classical, Romantic, and modern periods."},
{"cat":"Music","q":"Which composer is most closely associated with the Classical period rather than the Romantic period?","choices":["Haydn","Chopin","Liszt","Wagner"],"ans":0,"exp":"Joseph Haydn is a central composer of the Classical period."},
{"cat":"Music","q":"Which composer is strongly associated with musical Impressionism?","choices":["Debussy","Brahms","Wagner","Bach"],"ans":0,"exp":"Claude Debussy is strongly associated with musical Impressionism, though he disliked the label."},
{"cat":"Music","q":"What is a concerto usually designed to feature?","choices":["A soloist or group of soloists with an ensemble","Only a choir","Only percussion","A spoken narrator without instruments"],"ans":0,"exp":"A concerto typically contrasts one or more soloists with an orchestra or ensemble."},
{"cat":"Music","q":"What is a symphony traditionally written for?","choices":["Orchestra","Solo voice only","Solo piano only","String quartet only"],"ans":0,"exp":"A symphony is a large-scale instrumental work traditionally written for orchestra."},
{"cat":"Music","q":"What is an opera?","choices":["A staged dramatic work in which music and singing are central","A solo piano study","A short orchestral march","A form of tuning"],"ans":0,"exp":"Opera combines drama, singing, instrumental music, staging, and often dance."},
{"cat":"Music","q":"What does allegro generally indicate?","choices":["A fast or lively tempo","A very slow tempo","Silence","Gradually softer"],"ans":0,"exp":"Allegro generally indicates a fast, lively tempo."},
{"cat":"Music","q":"What does adagio generally indicate?","choices":["A slow tempo","A very fast tempo","Gradually louder","Repeat from the beginning"],"ans":0,"exp":"Adagio generally indicates a slow tempo."},
{"cat":"Music","q":"What does crescendo mean?","choices":["Gradually becoming louder","Gradually becoming softer","Suddenly stopping","Playing without vibrato"],"ans":0,"exp":"Crescendo means to increase volume gradually."},
{"cat":"Music","q":"What does diminuendo mean?","choices":["Gradually becoming softer","Gradually becoming faster","Gradually becoming louder","Returning to the opening"],"ans":0,"exp":"Diminuendo means to decrease volume gradually."},
{"cat":"Musical Instruments","q":"Which instrument is most closely associated with Niccolo Paganini?","choices":["Violin","Piano","Cello","Flute"],"ans":0,"exp":"Paganini was one of history's most famous violin virtuosos."},
{"cat":"Musical Instruments","q":"Which instrument is featured as the solo instrument in The Swan from The Carnival of the Animals?","choices":["Cello","Trumpet","Clarinet","Harp"],"ans":0,"exp":"Saint-Saens wrote The Swan for solo cello accompanied by two pianos."},
{"cat":"Musical Instruments","q":"Which orchestral instrument usually gives the tuning A before a concert?","choices":["Oboe","Trombone","Timpani","Cello"],"ans":0,"exp":"The orchestra traditionally tunes to an A sounded by the oboe."},
{"cat":"Musical Instruments","q":"Which is the lowest-pitched standard member of the orchestral string family?","choices":["Double bass","Cello","Viola","Violin"],"ans":0,"exp":"The double bass is the lowest-pitched standard orchestral string instrument."},
{"cat":"Musical Instruments","q":"Which instrument belongs to the woodwind family despite usually being made of metal today?","choices":["Flute","Trumpet","Trombone","French horn"],"ans":0,"exp":"The modern concert flute is usually metal but is classified as a woodwind instrument."},
{"cat":"Musical Instruments","q":"Which instrument uses a double reed?","choices":["Oboe","Clarinet","Flute","Trumpet"],"ans":0,"exp":"The oboe uses a double reed."},
{"cat":"Musical Instruments","q":"Which instrument uses a single reed?","choices":["Clarinet","Oboe","Bassoon","Flute"],"ans":0,"exp":"The clarinet uses a single reed attached to its mouthpiece."},
{"cat":"Musical Instruments","q":"Which brass instrument commonly uses a slide to change pitch?","choices":["Trombone","Trumpet","Tuba","French horn"],"ans":0,"exp":"The trombone commonly changes pitch with a telescoping slide."},
{"cat":"Musical Instruments","q":"Which percussion instrument can play definite pitches and is commonly tuned with pedals?","choices":["Timpani","Snare drum","Cymbals","Triangle"],"ans":0,"exp":"Timpani are tuned drums whose pitch can be adjusted, commonly with pedals."},
{"cat":"Musical Instruments","q":"How many strings does a standard modern violin have?","choices":["Four","Five","Six","Eight"],"ans":0,"exp":"A standard violin has four strings: G, D, A, and E."},
{"cat":"Music","q":"Which city is especially associated with Mozart, Haydn, Beethoven, and Schubert?","choices":["Vienna","Paris","London","Milan"],"ans":0,"exp":"Vienna was a major center of European classical music and is closely associated with these composers."},
{"cat":"Music","q":"Which composer was born in Salzburg?","choices":["Mozart","Beethoven","Bach","Brahms"],"ans":0,"exp":"Wolfgang Amadeus Mozart was born in Salzburg in 1756."},
{"cat":"Music","q":"Which composer was born in Bonn?","choices":["Beethoven","Mozart","Schubert","Haydn"],"ans":0,"exp":"Ludwig van Beethoven was born in Bonn."},
{"cat":"Music","q":"Which composer served for many years at the court of the Esterhazy family?","choices":["Haydn","Mozart","Beethoven","Schubert"],"ans":0,"exp":"Joseph Haydn spent much of his career in the service of the Esterhazy family."},
{"cat":"Music","q":"Which composer wrote more than 600 songs, including Erlkonig?","choices":["Schubert","Schumann","Brahms","Wolf"],"ans":0,"exp":"Franz Schubert was a prolific composer of Lieder and wrote Erlkonig."}
];

(() => {
  if(typeof QUESTIONS==='undefined' || !Array.isArray(QUESTIONS)) return;
  if(window.__sushiQuizClassicalMusicMerged) return;
  const existing=new Set(QUESTIONS.map(q=>`${q.cat}::${q.q}`));
  const additions=SUSHI_QUIZ_CLASSICAL_MUSIC.filter(q=>!existing.has(`${q.cat}::${q.q}`));
  QUESTIONS.push(...additions);
  window.__sushiQuizClassicalMusicMerged=true;
  if(typeof renderCategoryCards==='function') ['soloCatCards','localCatCards','onlineCatCards','buzzerCatCards'].forEach(renderCategoryCards);
  console.info(`Sushi Quiz classical music: added ${additions.length} questions (${QUESTIONS.length} total).`);
})();
