'use strict';
const $=id=>document.getElementById(id),LEDGER='sushitan_login_bonus_v1',COST=100,REFUND=30;
let filter='owned',busy=false,timer,lastPrize=null,returnFocus=null;
function readLedger(){const raw=localStorage.getItem(LEDGER);if(!raw)return {gems:0};const value=JSON.parse(raw);if(!value||typeof value!=='object'||Array.isArray(value))throw Error('保存データを読み込めません。');return value;}
function normalize(value){const g=value.gacha||{},a={...DEFAULT_AVATAR,...g.avatar};for(const k of ['hair','eyes','mouth','skin','hairColor'])if(!Number.isInteger(a[k])||a[k]<0||a[k]>=(k==='hair'?10:3))a[k]=0;if(!['male','female'].includes(a.gender))a.gender='male';const owned=[...new Set(['starter',...(Array.isArray(g.owned)?g.owned:[]).filter(id=>ITEMS.some(i=>i.id===id))])];
 if(g.version!==2){const legacy={chef:'hat-chef',royal:'hat-crown',explorer:'hat-explorer'};for(const [outfit,hat] of Object.entries(legacy))if(owned.includes(outfit)&&!owned.includes(hat))owned.push(hat);if(!Object.hasOwn(g.avatar||{},'hat'))a.hat=legacy[a.outfit]||null;}
 for(const slot of ['outfit','hat','accessory'])if(!owned.includes(a[slot])||!ITEMS.some(i=>i.id===a[slot]&&i.slot===slot))a[slot]=slot==='outfit'?'starter':null;
 return {version:2,avatar:a,owned,pulls:Number.isSafeInteger(g.pulls)&&g.pulls>=0?g.pulls:0};}
function balance(l){return Number.isSafeInteger(l.gems)&&l.gems>=0?l.gems:0;}
function state(){const l=readLedger();return {...normalize(l),gems:balance(l)};}
async function transaction(change){const run=()=>{const ledger=readLedger(),g=normalize(ledger);const result=change(ledger,g);ledger.gacha=g;localStorage.setItem(LEDGER,JSON.stringify(ledger));return result;};return navigator.locks? navigator.locks.request('sushitan-ledger',run):run();}
function fail(e){$('status').textContent=e.message||'保存できませんでした。ブラウザの保存設定を確認してください。';}
const partNames={hair:HAIR_NAMES,eyes:['ぱっちり','にこにこ','きりっと'],mouth:['ほほえみ','にっこり','おすまし'],skin:['ライト','ミディアム','ディープ'],hairColor:['ブラウン','キャラメル','ブルーブラック']};
function render(){try{const s=state();$('balance').textContent=s.gems.toLocaleString();if($('pull')){$('pull').disabled=busy||s.gems<COST;$('demo').disabled=busy;$('pullHelp').textContent=s.gems<COST?'100ジェムで1回。トップのログイン報酬で集めよう。':'同じアイテムが出たら、30ジェムが戻ります。';}if($('avatar')){$('avatar').innerHTML=avatarSVG(s.avatar);$('outfitName').textContent=ITEMS.find(x=>x.id===s.avatar.outfit).name;$('ownedCount').textContent=(s.owned.length-1)+' / 24 COLLECTED';renderEditor(s);renderAvatarControls(s);renderCloset(s);}}catch(e){fail(e);if($('pull'))$('pull').disabled=true;}}
function renderEditor(s){$('customizer').replaceChildren();const labels={eyes:'目',mouth:'口',skin:'肌の色',hairColor:'髪色'};for(const [key,label] of Object.entries(labels)){const b=document.createElement('button');b.className='part';b.disabled=busy;b.setAttribute('aria-label',`${label}：${partNames[key][s.avatar[key]]}。次のパターンへ`);b.innerHTML=`<small>${label} ↻</small><b>${partNames[key][s.avatar[key]]}</b>`;b.onclick=async()=>{try{await transaction((l,g)=>g.avatar[key]=(g.avatar[key]+1)%partNames[key].length);render();$('saveNote').textContent='✓ アバターを保存しました';}catch(e){fail(e);}};$('customizer').append(b);}const random=document.createElement('button');random.className='part';random.disabled=busy;random.innerHTML='<small>おまかせ</small><b>🎲 ランダム</b>';random.onclick=async()=>{try{await transaction((l,g)=>{for(const k of Object.keys(partNames))g.avatar[k]=Math.floor(Math.random()*partNames[k].length);});render();}catch(e){fail(e);}};$('customizer').append(random);}
function renderAvatarControls(s){$('genderOptions').replaceChildren();for(const [value,label] of [['male','男性'],['female','女性']]){const b=document.createElement('button');b.textContent=label;b.className=s.avatar.gender===value?'active':'';b.disabled=busy;b.setAttribute('aria-pressed',String(s.avatar.gender===value));b.onclick=async()=>{try{await transaction((l,g)=>g.avatar.gender=value);render();}catch(e){fail(e);}};$('genderOptions').append(b);}
 $('hairName').textContent=HAIR_NAMES[s.avatar.hair];$('hairOptions').replaceChildren();HAIR_NAMES.forEach((name,i)=>{const b=document.createElement('button');b.className='hairOption'+(s.avatar.hair===i?' active':'');b.disabled=busy;b.setAttribute('aria-label',name);b.setAttribute('aria-pressed',String(s.avatar.hair===i));b.innerHTML=avatarSVG({...s.avatar,hair:i,hat:null,accessory:null})+'<span>'+name+'</span>';b.onclick=async()=>{try{await transaction((l,g)=>g.avatar.hair=i);render();}catch(e){fail(e);}};$('hairOptions').append(b);});
 $('equipment').replaceChildren();for(const [slot,label] of [['hat','帽子'],['accessory','アクセサリー']]){const item=ITEMS.find(i=>i.id===s.avatar[slot]),row=document.createElement('div'),name=document.createElement('span');name.textContent=label+'：'+(item?item.name:'なし');row.append(name);if(item){const remove=document.createElement('button');remove.textContent='外す';remove.disabled=busy;remove.setAttribute('aria-label',label+'を外す');remove.onclick=async()=>{try{await transaction((l,g)=>g.avatar[slot]=null);render();}catch(e){fail(e);}};row.append(remove);}$('equipment').append(row);}}
function renderCloset(s){$('items').replaceChildren();const items=ITEMS.filter(i=>filter==='owned'?s.owned.includes(i.id):filter==='all'||i.rarity===filter||i.slot===filter);if(!items.length){$('items').innerHTML='<p class="empty">まだ服がありません。「すべて」でラインナップを見てみよう。</p>';return;}items.forEach(item=>{const owned=s.owned.includes(item.id),equipped=s.avatar[item.slot]===item.id,b=document.createElement('button');b.className='item'+(owned?'':' locked')+(equipped?' equipped':'');b.dataset.rarity=item.rarity;b.disabled=!owned||busy;b.setAttribute('aria-label',`${item.name} ${equipped?'着用中':owned?'着替える':'未入手'}`);b.innerHTML=`<span class="tag">${item.rarity==='STARTER'?'BASIC':item.rarity} · ${{outfit:'服',hat:'帽子',accessory:'アクセサリー'}[item.slot]}</span>${avatarSVG(s.avatar,item.id)}<strong>${item.name}</strong><small>${equipped?'✓ 着用中':owned?'着替える':'🔒 未入手'}</small>`;b.onclick=()=>equip(item.id);$('items').append(b);});}
async function equip(id){try{await transaction((l,g)=>{if(!g.owned.includes(id))throw Error('この服はまだ持っていません。');const item=ITEMS.find(i=>i.id===id);g.avatar[item.slot]=id;});render();$('saveNote').textContent='✓ コーデを保存しました';}catch(e){fail(e);}}
function roll(){const n=crypto.getRandomValues(new Uint32Array(1))[0]/4294967296,rarity=n<.6?'N':n<.9?'R':'SR',pool=ITEMS.filter(i=>i.rarity===rarity);return pool[Math.floor(crypto.getRandomValues(new Uint32Array(1))[0]/4294967296*pool.length)];}
async function pull(demo=false){if(busy)return;busy=true;$('status').textContent='';render();try{let prize;if(demo){prize={item:roll(),duplicate:false,demo:true,avatar:state().avatar};}else{prize=await transaction((ledger,g)=>{const gems=balance(ledger);if(gems<COST)throw Error('ジェムが足りません。');const item=roll(),duplicate=g.owned.includes(item.id);ledger.gems=gems-COST+(duplicate?REFUND:0);if(!duplicate)g.owned.push(item.id);g.pulls++;return {item,duplicate,demo:false,avatar:{...g.avatar}};});}lastPrize=prize;showReveal();render();}catch(e){busy=false;fail(e);render();}}
function showReveal(){returnFocus=document.activeElement;$('reveal').dataset.rarity=lastPrize.item.rarity;$('opening').hidden=false;$('prize').hidden=true;$('reveal').showModal();timer=setTimeout(revealPrize,window.matchMedia('(prefers-reduced-motion: reduce)').matches?100:1800);}
function revealPrize(){clearTimeout(timer);if(!$('reveal').open||!$('prize').hidden)return;const p=lastPrize;$('opening').hidden=true;$('prize').hidden=false;$('prizeRarity').textContent=p.item.rarity;$('newLabel').textContent=p.demo?'おためし':p.duplicate?'WELCOME BACK!':'NEW ITEM!';$('prizeAvatar').innerHTML=avatarSVG(p.avatar,p.item.id);$('prizeName').textContent=p.item.name;$('prizeNote').textContent=p.demo?'演出のおためしです。ジェムは消費せず、アイテムは保存されません。':p.duplicate?'持っているアイテムでした。30ジェムを返却しました。':'クローゼットに追加しました。あたらしい自分に着替えよう！';$('equip').hidden=p.demo;for(let i=0;i<20&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches;i++){const d=document.createElement('i');d.className='confetti';d.style.left=Math.random()*100+'%';d.style.background=['#e7b861','#85a999','#e58b73','#a99fbc'][i%4];d.style.animationDelay=Math.random()*.4+'s';$('reveal').append(d);setTimeout(()=>d.remove(),2200);}($('equip').hidden?$('keep'):$('equip')).focus();}
function closeReveal(){clearTimeout(timer);$('reveal').close();busy=false;render();$('pull').disabled?$('demo').focus():$('pull').focus();}
if($('pull')){$('pull').onclick=()=>pull(false);$('demo').onclick=()=>pull(true);$('skip').onclick=revealPrize;$('close').onclick=closeReveal;$('keep').onclick=closeReveal;$('equip').onclick=()=>{if(!lastPrize||lastPrize.demo)return;location.href='sushi-avatar.html?item='+encodeURIComponent(lastPrize.item.id);};$('reveal').addEventListener('cancel',e=>{e.preventDefault();closeReveal();});}
if($('filters'))$('filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$('filters').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render();});
window.addEventListener('storage',e=>{if(e.key===LEDGER)render();});window.addEventListener('focus',render);window.addEventListener('pageshow',render);render();
if($('avatar')){const requested=new URLSearchParams(location.search).get('item');if(requested&&ITEMS.some(i=>i.id===requested)){equip(requested).then(()=>history.replaceState(null,'',location.pathname));}}
