'use strict';
const $=id=>document.getElementById(id),LEDGER='sushitan_login_bonus_v1',COST=100,REFUND=30;
let filter='owned',busy=false,timer,lastPrize=null,stageTimers=[];
function readLedger(){const raw=localStorage.getItem(LEDGER);if(!raw)return {gems:0};const value=JSON.parse(raw);if(!value||typeof value!=='object'||Array.isArray(value))throw Error('保存データを読み込めません。');return value;}
function normalize(value){const g=value.gacha||{},old=g.avatar||{},gender=['male','female'].includes(old.gender)?old.gender:'male',a={...DEFAULT_AVATAR,...old,gender};if(old.outfit&&!old.top)a.top=old.outfit;delete a.outfit;const owned=[...new Set(['starter','basic-bottom',...(Array.isArray(g.owned)?g.owned:[]).filter(id=>ITEMS.some(i=>i.id===id))])];for(const slot of ['top','bottom','hat','accessory']){const id=a[slot],item=ITEMS.find(i=>i.id===id&&i.slot===slot);if(!id||!owned.includes(id)||!item||!compatible(item,gender))a[slot]=slot==='top'?'starter':slot==='bottom'?'basic-bottom':null;}return {version:3,avatar:a,owned,pulls:Number.isSafeInteger(g.pulls)?g.pulls:0};}
function balance(l){return Number.isSafeInteger(l.gems)&&l.gems>=0?l.gems:0}function state(){const l=readLedger();return {...normalize(l),gems:balance(l)}}async function transaction(change){const run=()=>{const ledger=readLedger(),g=normalize(ledger),r=change(ledger,g);ledger.gacha=g;localStorage.setItem(LEDGER,JSON.stringify(ledger));return r};return navigator.locks?navigator.locks.request('sushitan-ledger',run):run()}function fail(e){if($('status'))$('status').textContent=e.message||'保存できませんでした。'}
async function ownerTestRefill(){if(!location.hash.startsWith('#dev='))return;const secret=decodeURIComponent(location.hash.slice(5)),digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)),hex=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');history.replaceState(null,'',location.pathname+location.search);if(hex!=='5c61195df1a885d060bdd507922dbb2718bcdb6bf16eb0e4589de9e376f65a8b')return;await transaction(l=>l.gems=Math.max(balance(l),5000));$('status').textContent='🧪 テスト用：すしジェムを5000まで補充しました。'}
function render(){try{const s=state();$('balance').textContent=s.gems.toLocaleString();$('pull').disabled=busy||s.gems<COST;$('demo').disabled=busy;$('pullHelp').textContent=s.gems<COST?'100ジェムで1回。トップのログイン報酬で集めよう。':'同じアイテムが出たら、30ジェムが戻ります。';}catch(e){fail(e)}}
function roll(){const n=crypto.getRandomValues(new Uint32Array(1))[0]/4294967296,rarity=n<.6?'N':n<.9?'R':'SR',pool=ITEMS.filter(i=>i.rarity===rarity);return pool[Math.floor(Math.random()*pool.length)]}
async function pull(demo=false){if(busy)return;busy=true;$('status').textContent='';render();try{let prize;if(demo)prize={item:roll(),duplicate:false,demo:true,avatar:state().avatar};else prize=await transaction((ledger,g)=>{const gems=balance(ledger);if(gems<COST)throw Error('ジェムが足りません。');const item=roll(),duplicate=g.owned.includes(item.id);ledger.gems=gems-COST+(duplicate?REFUND:0);if(!duplicate)g.owned.push(item.id);g.pulls++;return {item,duplicate,demo:false,avatar:{...g.avatar}}});lastPrize=prize;showReveal();render()}catch(e){busy=false;fail(e);render()}}
function later(fn,ms){const t=setTimeout(fn,ms);stageTimers.push(t)}function clearStages(){stageTimers.forEach(clearTimeout);stageTimers=[]}
function showReveal(){clearStages();const rarity=lastPrize.item.rarity,body=$('reveal').querySelector('.revealBody');$('reveal').dataset.rarity=rarity;body.classList.remove('hot');$('opening').hidden=false;$('prize').hidden=true;$('openingText').textContent='大将が握っています…';$('reveal').showModal();if(matchMedia('(prefers-reduced-motion: reduce)').matches){timer=setTimeout(revealPrize,100);return}later(()=>$('openingText').textContent='寿司が流れてきた…',900);if(rarity==='R'){later(()=>{$('openingText').textContent='皿が光っている…！';body.classList.add('hot')},1450);timer=setTimeout(revealPrize,2700)}else if(rarity==='SR'){later(()=>{$('openingText').textContent='……おや？';body.classList.add('hot')},1250);later(()=>$('openingText').textContent='！？ 虹色に変わった！！',1750);timer=setTimeout(revealPrize,3100)}else timer=setTimeout(revealPrize,2250)}
function revealPrize(){clearTimeout(timer);clearStages();if(!$('reveal').open||!$('prize').hidden)return;const p=lastPrize;$('opening').hidden=true;$('prize').hidden=false;$('prizeRarity').textContent=p.item.rarity;$('newLabel').textContent=p.demo?'おためし':p.duplicate?'WELCOME BACK!':'NEW ITEM!';$('prizeAvatar').innerHTML=avatarSVG(p.avatar,p.item.id);$('prizeName').textContent=p.item.name;$('prizeNote').textContent=p.demo?'演出のおためしです。ジェムは消費せず、アイテムは保存されません。':p.duplicate?'持っているアイテムでした。30ジェムを返却しました。':'クローゼットに追加しました！';$('equip').hidden=p.demo;for(let i=0;i<(p.item.rarity==='SR'?45:p.item.rarity==='R'?28:18);i++){const d=document.createElement('i');d.className='confetti';d.style.left=Math.random()*100+'%';d.style.background=['#e7b861','#85a999','#e58b73','#a99fbc'][i%4];d.style.animationDelay=Math.random()*.4+'s';$('reveal').append(d);setTimeout(()=>d.remove(),2200)}}
function closeReveal(){clearTimeout(timer);clearStages();$('reveal').close();busy=false;render()}
$('pull').onclick=()=>pull(false);$('demo').onclick=()=>pull(true);$('skip').onclick=revealPrize;$('close').onclick=closeReveal;$('keep').onclick=closeReveal;$('equip').onclick=()=>{if(lastPrize&&!lastPrize.demo)location.href='sushi-avatar.html?item='+encodeURIComponent(lastPrize.item.id)};$('reveal').addEventListener('cancel',e=>{e.preventDefault();closeReveal()});window.addEventListener('storage',e=>{if(e.key===LEDGER)render()});window.addEventListener('focus',render);ownerTestRefill().then(render).catch(fail);render();