'use strict';
(()=>{
  if(window.__sushiSiteTaskbarLoaded)return;window.__sushiSiteTaskbarLoaded=true;
  const KEY='sushitan_login_bonus_v1';
  const QUESTS={
    sushitan:{label:'すし単',icon:'🍣',goal:30,reward:5,unit:'問'},
    run:{label:'すしRUN',icon:'🏃',goal:1500,reward:5,unit:'m'},
    world:{label:'す界し',icon:'🌍',goal:5,reward:3,unit:'問'},
    talk:{label:'すしTalk',icon:'💬',goal:10,reward:3,unit:'問'}
  };
  const day=()=>{const d=new Date();d.setHours(d.getHours()-6);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return x&&typeof x==='object'?x:{}}catch{return {}}}
  function ensure(l){const today=day();if(!l.dailyQuests||l.dailyQuests.day!==today)l.dailyQuests={day:today,progress:{sushitan:0,run:0,world:0,talk:0},claimed:{sushitan:false,run:false,world:false,talk:false},chestClaimed:false,chestReward:0};for(const k of Object.keys(QUESTS)){l.dailyQuests.progress[k]=Math.max(0,Number(l.dailyQuests.progress[k])||0);l.dailyQuests.claimed[k]=!!l.dailyQuests.claimed[k]}return l.dailyQuests}
  function write(l){localStorage.setItem(KEY,JSON.stringify(l));window.dispatchEvent(new CustomEvent('sushi-daily-quest-change'))}
  function toast(text){let t=document.getElementById('sushiTaskToast');if(!t){t=document.createElement('div');t.id='sushiTaskToast';document.body.append(t)}t.textContent=text;t.classList.remove('show');void t.offsetWidth;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2200)}
  function update(type,value,mode='add'){
    if(!QUESTS[type])return state();const l=read(),q=ensure(l),def=QUESTS[type];if(q.claimed[type])return state();q.progress[type]=mode==='set'?Math.max(q.progress[type],Number(value)||0):q.progress[type]+Math.max(0,Number(value)||0);q.progress[type]=Math.min(q.progress[type],def.goal);
    if(q.progress[type]>=def.goal&&!q.claimed[type]){q.claimed[type]=true;l.gems=(Number.isSafeInteger(l.gems)?l.gems:0)+def.reward;toast(`✅ ${def.label} 達成！ +${def.reward}💎`);navigator.vibrate?.([18,28,35]);}
    write(l);render();return state();
  }
  function state(){const l=read(),q=ensure(l);return {day:q.day,progress:{...q.progress},claimed:{...q.claimed},chestClaimed:q.chestClaimed,chestReward:q.chestReward||0,gems:Number.isSafeInteger(l.gems)?l.gems:0}}
  function chest(){const l=read(),q=ensure(l);if(q.chestClaimed||!Object.keys(QUESTS).every(k=>q.claimed[k]))return;const r=Math.random(),amount=r<.60?5:r<.90?10:r<.98?15:30;q.chestClaimed=true;q.chestReward=amount;l.gems=(Number.isSafeInteger(l.gems)?l.gems:0)+amount;write(l);render();toast(`🎁 デイリーコンプリート！ +${amount}💎`);navigator.vibrate?.([30,35,30,35,70]);}
  function open(){document.getElementById('sushiDailySheet')?.classList.add('open');render()}
  function close(){document.getElementById('sushiDailySheet')?.classList.remove('open')}
  window.SushiDailyQuest={add:(t,n=1)=>update(t,n,'add'),set:(t,n)=>update(t,n,'set'),state,open};

  const css=document.createElement('style');css.id='sushiTaskbarStyle';css.textContent=`
#sushiTaskbar{position:fixed;left:50%;bottom:max(8px,env(safe-area-inset-bottom));transform:translateX(-50%);width:min(560px,calc(100% - 20px));height:64px;z-index:99990;background:rgba(255,253,248,.96);border:1px solid #eadfce;border-radius:22px;box-shadow:0 10px 35px rgba(15,23,42,.20);display:grid;grid-template-columns:repeat(4,1fr);overflow:hidden;backdrop-filter:blur(14px);font-family:system-ui,-apple-system,'Segoe UI',sans-serif}
#sushiTaskbar a,#sushiTaskbar button{position:relative;border:0;background:transparent;text-decoration:none;color:#31413d;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;font:850 10px/1.1 system-ui;cursor:pointer;padding:4px}#sushiTaskbar a:not(:last-child),#sushiTaskbar button:not(:last-child){border-right:1px solid #eee6d8}#sushiTaskbar .ico{font-size:23px;line-height:1}#sushiTaskbar .mini{font-size:8px;color:#8a877d;font-weight:750}#sushiTaskbar .badge{position:absolute;top:5px;right:13%;min-width:18px;height:18px;padding:0 4px;border-radius:999px;background:#f4511e;color:#fff;display:grid;place-items:center;font-size:8px;border:2px solid #fff}#sushiTaskToast{position:fixed;left:50%;bottom:86px;transform:translate(-50%,12px);opacity:0;z-index:100001;background:#173f37;color:white;padding:11px 16px;border-radius:999px;font:900 12px/1.2 system-ui;box-shadow:0 8px 25px #0004;pointer-events:none;transition:.2s;white-space:nowrap}#sushiTaskToast.show{opacity:1;transform:translate(-50%,0)}
#sushiDailySheet{position:fixed;inset:0;z-index:99999;background:rgba(20,35,32,.54);display:none;align-items:flex-end;justify-content:center;font-family:system-ui,-apple-system,'Segoe UI',sans-serif}#sushiDailySheet.open{display:flex}.sdq-card{width:min(560px,100%);max-height:78dvh;overflow:auto;background:#fffdf8;border-radius:25px 25px 0 0;padding:18px 18px calc(82px + env(safe-area-inset-bottom));box-shadow:0 -12px 40px #0003;color:#243b37}.sdq-head{display:flex;justify-content:space-between;align-items:center}.sdq-head h2{margin:0;font-size:19px}.sdq-close{border:0;background:#f3ede0;border-radius:50%;width:34px;height:34px;font-size:20px}.sdq-note{font-size:11px;color:#7c8178;margin:5px 0 14px}.sdq-row{display:grid;grid-template-columns:36px 1fr auto;gap:10px;align-items:center;border:1px solid #eee2cf;border-radius:15px;padding:10px;margin:8px 0;background:#fff}.sdq-row.done{background:#eff8ef;border-color:#b8d8ba}.sdq-icon{font-size:24px}.sdq-name{font-size:12px;font-weight:900}.sdq-progress{height:7px;background:#eee8dd;border-radius:99px;overflow:hidden;margin-top:6px}.sdq-progress i{display:block;height:100%;background:#f4511e;border-radius:99px}.sdq-num{font-size:10px;color:#777;margin-top:4px}.sdq-reward{font-size:11px;font-weight:900;color:#9b6d19;white-space:nowrap}.sdq-chest{width:100%;margin-top:13px;border:0;border-radius:16px;padding:14px;background:linear-gradient(180deg,#f7c95c,#e7a82a);color:#5b3b09;font-weight:1000;font-size:14px;box-shadow:0 5px 12px #d69c2933}.sdq-chest:disabled{background:#e7e2d8;color:#918d84;box-shadow:none}.sdq-chest.claimed{background:#e9f4e8;color:#397044}
body.sushi-taskbar-on{padding-bottom:max(78px,calc(70px + env(safe-area-inset-bottom)))}body.sushi-taskbar-on #homeAvatarWalker{bottom:72px!important}body.sushi-taskbar-on #sushiAvatarWidget{bottom:76px!important}body.sushi-taskbar-on #sushiGemToast{bottom:84px!important}body.sushi-taskbar-on #controlBar{bottom:64px!important}
@media(max-width:600px){#sushiTaskbar{left:0;right:0;bottom:0;transform:none;width:100%;height:62px;border-radius:16px 16px 0 0;border-left:0;border-right:0;border-bottom:0}#sushiTaskbar .ico{font-size:21px}#sushiTaskbar .badge{right:9%}#sushiTaskToast{bottom:76px}.sdq-card{padding-bottom:calc(76px + env(safe-area-inset-bottom))}body.sushi-taskbar-on #homeAvatarWalker{bottom:64px!important}body.sushi-taskbar-on #sushiAvatarWidget{bottom:67px!important}body.sushi-taskbar-on #controlBar{bottom:62px!important}}
`;document.head.append(css);
  const bar=document.createElement('nav');bar.id='sushiTaskbar';bar.setAttribute('aria-label','すし単メニュー');bar.innerHTML=`<a id="sushiLoginTab" href="/index.html#loginBonus"><span class="ico">🎁</span><span>ログボ</span><small class="mini"></small></a><a href="/sushigacha/sushi-gacha.html"><span class="ico">🍣</span><span>ガチャ</span><small class="mini">💎 <b id="sushiBarGems">0</b></small></a><a href="/sushigacha/sushi-avatar.html"><span class="ico">👤</span><span>アバター</span><small class="mini">きせかえ</small></a><button id="sushiDailyTab" type="button"><span class="ico">✅</span><span>デイリー</span><small class="mini">0 / 4</small><i class="badge">0</i></button>`;document.body.append(bar);document.body.classList.add('sushi-taskbar-on');
  const sheet=document.createElement('div');sheet.id='sushiDailySheet';sheet.innerHTML=`<div class="sdq-card" role="dialog" aria-modal="true" aria-label="デイリークエスト"><div class="sdq-head"><h2>✅ デイリークエスト</h2><button class="sdq-close" type="button" aria-label="閉じる">×</button></div><p class="sdq-note">毎朝6:00リセット。達成するとジェムを自動で受け取れます。</p><div id="sdqRows"></div><button id="sdqChest" class="sdq-chest" type="button"></button></div>`;document.body.append(sheet);
  sheet.querySelector('.sdq-close').onclick=close;sheet.addEventListener('click',e=>{if(e.target===sheet)close()});bar.querySelector('#sushiDailyTab').onclick=open;sheet.querySelector('#sdqChest').onclick=chest;
  const login=bar.querySelector('#sushiLoginTab');if(location.pathname==='/'||/\/index\.html$/i.test(location.pathname)){login.onclick=e=>{const el=document.getElementById('loginBonus');if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth',block:'center'})}}}
  function render(){const l=read(),q=ensure(l),done=Object.keys(QUESTS).filter(k=>q.claimed[k]).length;bar.querySelector('#sushiBarGems').textContent=(Number.isSafeInteger(l.gems)?l.gems:0).toLocaleString();const daily=bar.querySelector('#sushiDailyTab');daily.querySelector('.mini').textContent=`${done} / 4`;daily.querySelector('.badge').textContent=done;const got=Array.isArray(l.dailyGemClaims)&&l.dailyGemClaims.includes(day());login.querySelector('.mini').textContent=got?'受取済':'毎日 +10💎';const rows=sheet.querySelector('#sdqRows');rows.innerHTML=Object.entries(QUESTS).map(([k,d])=>{const p=Math.min(d.goal,q.progress[k]||0),pct=Math.round(p/d.goal*100);return `<div class="sdq-row ${q.claimed[k]?'done':''}"><div class="sdq-icon">${d.icon}</div><div><div class="sdq-name">${d.label}</div><div class="sdq-progress"><i style="width:${pct}%"></i></div><div class="sdq-num">${Math.floor(p)} / ${d.goal}${d.unit}</div></div><div class="sdq-reward">${q.claimed[k]?'✓ GET':`+${d.reward}💎`}</div></div>`}).join('');const c=sheet.querySelector('#sdqChest'),all=done===4;if(q.chestClaimed){c.disabled=true;c.classList.add('claimed');c.textContent=`🎁 コンプリート報酬 +${q.chestReward}💎 受取済み`}else if(all){c.disabled=false;c.classList.remove('claimed');c.textContent='🎁 デイリーコンプリート宝箱を開ける！'}else{c.disabled=true;c.classList.remove('claimed');c.textContent=`🔒 あと ${4-done} 個でコンプリート宝箱`}}
  render();window.addEventListener('storage',e=>{if(e.key===KEY)render()});window.addEventListener('sushi-daily-quest-change',render);window.addEventListener('focus',render);window.addEventListener('pageshow',render);

  // Page-specific automatic progress hooks.
  const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  if(page==='sushitan.html'){
    const states=new WeakMap();const inspect=el=>{const now=el.classList.contains('good');const before=states.get(el)||false;if(now&&!before)update('sushitan',1);states.set(el,now)};const watch=()=>document.querySelectorAll('.feedback').forEach(inspect);new MutationObserver(ms=>{ms.forEach(m=>{if(m.target instanceof Element&&m.target.matches('.feedback'))inspect(m.target);m.addedNodes.forEach?.(n=>{if(n instanceof Element){if(n.matches('.feedback'))inspect(n);n.querySelectorAll?.('.feedback').forEach(inspect)}})})}).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});watch();
  }
  if(page==='sushitalk.html'){
    const seen=new WeakSet();const scan=()=>document.querySelectorAll('.delta').forEach(el=>{if(seen.has(el))return;seen.add(el);const n=Number((el.textContent||'').replace(/[^+\-\d.]/g,''));if(n>0)update('talk',1)});new MutationObserver(scan).observe(document.documentElement,{subtree:true,childList:true});scan();
  }
  if(page==='sukaishi_world_study_v03.html'||page==='sukaishi.html'){
    let was=false;const check=()=>{const el=document.getElementById('judge');if(!el)return;const now=/✓\s*CORRECT/i.test(el.textContent||'');if(now&&!was)update('world',1);was=now};new MutationObserver(check).observe(document.documentElement,{subtree:true,childList:true,characterData:true});check();
  }
})();