const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');const root=path.join(__dirname,'..');
function extract(file,name){const s=fs.readFileSync(path.join(root,file),'utf8'),m=new RegExp('(?:async\\s+)?function\\s+'+name+'\\s*\\([^)]*\\)\\s*\\{').exec(s);assert(m,file+':'+name);let i=m.index+m[0].length,depth=1,quote='';for(;depth;i++){const c=s[i];if(quote){if(c==='\\'){i++;continue}if(c===quote)quote='';continue}if(c==='"'||c==="'"||c==='`')quote=c;else if(c==='{')depth++;else if(c==='}')depth--}return s.slice(m.index,i)}
function harness(file,name,extras={}){const calls=[],els=new Map(),el=id=>{if(!els.has(id))els.set(id,{textContent:'',disabled:false,dataset:{},classList:{add(){},remove(){}},replaceChildren(){},appendChild(){}});return els.get(id)};const c={SushiScores:{save:async(p,o)=>{calls.push({p:{...p},o});return {saved:false,queued:true}}},SushiPlayer:{getName:()=> '共通テスト名'},document:{getElementById:el,querySelector:el},$:(id)=>el(id),Math,Number,console,loadRanking(){},showSlashRanking(){},loadHayaoshiRanking(){},setRankingTabUI(){},window:{},...extras};c.saveStatus=el('saveStatus');vm.createContext(c);vm.runInContext(extract(file,name),c);return {c,calls,el,run:(...a)=>c[name](...a)}}
async function main(){
 for(const file of ['sushitan.html','shinotan.html','antonitan.html']){const h=harness(file,'saveHighScore',{GAME:{scoreSavedThisRound:false,maxCombo:8,reviewMode:false},currentMode:'core',currentSushiLevel:'all',MODE_SUSHI:'core',getDbModeForGame:()=> 'core',normalizeModeForDb:m=>m});await h.run(123,90);await h.run(123,90);assert.equal(h.calls.length,1);assert.equal(h.calls[0].p.p_score,123);h.c.GAME.scoreSavedThisRound=false;h.c.GAME.reviewMode=true;await h.run(125,95);assert.equal(h.calls.length,1)}
 const run=harness('sushi_run.html','saveRanking',{distance:123.9,combo:5,lastSaved:false});await run.run();await run.run();assert.equal(run.calls.length,1);assert.equal(run.calls[0].p.p_mode,'wordrush');
 const run3=harness('sushi-run3D.html','saveRanking',{state:{distance:33.5,maxCombo:2,correctCount:4,total:5}});await run3.run();await run3.run();assert.equal(run3.calls.length,1);assert.equal(run3.calls[0].p.p_accuracy,80);
 const slash=harness('sushigiri.html','saveSlashRanking',{score:150,maxCombo:9,rankingSaved:false,slashMode:()=> 'sushi_slash'});await slash.run();await slash.run();assert.equal(slash.calls.length,1);
 const clock=harness('sushi_clock.html','saveRanking',{state:{mode:'team',score:123,combo:3}});await clock.run();assert.equal(clock.calls.length,0);clock.c.state.mode='typing';await clock.run();await clock.run();assert.equal(clock.calls.length,1);assert.equal(clock.calls[0].p.p_mode,'clock_typing');
 const idiom=harness('sushi_idiom (1).html','submitScore',{state:{mode:'review',score:500,correct:3,wrong:1,maxCombo:2},MODE_NAME:'sushi_idiom'});await idiom.run();assert.equal(idiom.calls.length,0);idiom.c.state.mode='normal';await idiom.run();await idiom.run();assert.equal(idiom.calls.length,1);assert.equal(idiom.calls[0].p.p_accuracy,75);assert(idiom.calls[0].o.daily);
 const fast=harness('sushi_hayaoshi.html','saveSoloScore',{lastSoloResult:{score:41,correct:5,accuracy:83,level:'normal'},getHayaoshiMode:l=>'hayaoshi_'+l});await fast.run();await fast.run();assert.equal(fast.calls.length,1);
 for(const file of ['sushi_quiz.html','sushi_quiz_core.html']){const quiz=harness(file,'saveSoloScore',{solo:{streak:8,count:9}});await quiz.run();await quiz.run();assert.equal(quiz.calls.length,1);assert.equal(quiz.calls[0].p.p_score,8);assert.equal(quiz.calls[0].p.p_mode,'sushi_quiz_solo')}
 const type=harness('sushitype.html','saveScore',{state:{score:123,maxCombo:4},getScoreMode:()=> 'typing_game_endless',getAccuracy:()=>98});await type.run();await type.run();type.c.state.score=183;await type.run();assert.equal(type.calls.length,2);assert.equal(type.calls[0].o.target,'typing');
 const dungeon=harness('sushidungeon/ranking.js','saveSnapshot',{MODE:'sushi_dungeon',encode:(floor,turn)=>floor*1000-turn});await dungeon.run({floor:3,turn:20,level:4,testMode:true});assert.equal(dungeon.calls.length,0);await dungeon.run({floor:3,turn:20,level:4});assert.equal(dungeon.calls[0].p.p_score,2980);
 const local=[];const kobun=harness('sushikobun.html','saveScore',{score:9,MODE:'kobun_connect',saveLocal:e=>local.push(e)});await kobun.run();await kobun.run();assert.equal(local.length,1);assert.equal(local[0].player_name,'共通テスト名');assert.equal(local[0].accuracy,90);
 // Make sure the automatic calls are present in the actual result/checkpoint code.
 for(const [file,entry,call] of [['sushi_run.html','gameOver','saveRanking();'],['sushi-run3D.html','finish','saveRanking();'],['sushigiri.html','initRankingResult','saveSlashRanking();'],['sushi_clock.html','finishGame','saveRanking();'],['sushikobun.html','endGame','saveScore();'],['sushi_hayaoshi.html','endGame','saveSoloScore();'],['sushi_quiz.html','ansSolo','saveSoloScore();'],['sushi_quiz_core.html','ansSolo','saveSoloScore();'],['sushitype.html','finishTimeAttack','saveScore()'],['sushitype.html','advancePrompt','saveScore()'],['sushitype.html','winBattleStage','saveScore()'],['sushitype.html','loseBattle','saveScore()']])assert(extract(file,entry).includes(call),file+':'+entry);
 console.log('PASS: 14 ranking adapters, no duplicate terminal submissions, review/team/test exclusions, captured scores, typing target/checkpoints, local Kobun preservation, automatic result hooks');
}
main().catch(e=>{console.error(e);process.exitCode=1});
