// Run with PLAYWRIGHT_MODULE pointing to an installed Playwright package if needed.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),KEY='sushitan_login_bonus_v1';
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/avatar-home-test.html'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><button id="underlying">Content button</button><script>window.__sushiSiteTaskbarLoaded=true;</script><script src="sushigacha/home-avatar-walker.js"></script></body></html>');}if(u.pathname==='/avatar-widget-test.html'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><body><script src="sushigacha/avatar-widget.js"></script></body>');}let f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(f,(e,d)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript'})[path.extname(f)]||'application/octet-stream');res.end(d);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
try{
const context=await browser.newContext({viewport:{width:1360,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());
const original={gems:777,streak:4,lastDay:'2026-10-01',unknownLedger:{keep:'yes'},gacha:{version:1,avatar:{outfit:'chef',gender:'female',hair:4,eyes:6,mouth:1,skin:2,faceShape:2,expression:1,pet:1,aura:4,futureField:17},owned:['chef','acc-glasses','unknown-future-item'],pulls:13,futureGacha:{keep:1}}};
await page.goto(origin+'/sushigacha/sushi-avatar.html');await page.evaluate(({KEY,original})=>localStorage.setItem(KEY,JSON.stringify(original)),{KEY,original});await page.reload();
assert.equal(await page.locator('#faceShape').inputValue(),'2');assert.equal(await page.locator('#expression').inputValue(),'1');assert.equal(await page.locator('#pet').inputValue(),'1');assert.equal(await page.locator('#aura').inputValue(),'4');assert.deepEqual(await page.evaluate(KEY=>JSON.parse(localStorage.getItem(KEY)),KEY),original);
assert.equal(await page.locator('[data-gender="female"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.closet').count(),0);assert.equal(await page.locator('#equipment-top option[value="studio-wizard"]').count(),0);
await page.goto(origin+'/sushigacha/sushi-avatar.html?item=studio-wizard');assert.equal(await page.locator('#equipLook').isDisabled(),true);assert.deepEqual(await page.evaluate(KEY=>JSON.parse(localStorage.getItem(KEY)),KEY),original);
assert.equal(await page.evaluate(async()=>{try{await SushiAvatarStore.equip({...SushiAvatarV2.defaults,top:'studio-wizard'});return false;}catch{return true;}}),true);
await page.locator('#cancelLook').click();await page.locator('[data-gender="male"]').click();await page.locator('#equipment-top').selectOption('starter');await page.locator('#equipment-top').selectOption('chef');assert.equal(await page.locator('#expression').inputValue(),'1');await page.locator('#faceShape').selectOption('1');await page.locator('#expression').selectOption('5');
// A reward arrives after opening the editor; equip must merge against the latest ledger.
await page.evaluate(KEY=>{const l=JSON.parse(localStorage.getItem(KEY));l.gems+=25;l.daily={progress:12};localStorage.setItem(KEY,JSON.stringify(l));},KEY);
await page.locator('#equipLook').click();await page.waitForFunction(()=>document.getElementById('status').textContent==='コーデを保存しました。');
let saved=await page.evaluate(KEY=>JSON.parse(localStorage.getItem(KEY)),KEY);assert.equal(saved.gacha.avatar.gender,'male');assert.equal(saved.gems,802);assert.equal(saved.gacha.pulls,13);assert.equal(saved.gacha.avatar.futureField,17);assert.deepEqual(saved.gacha.futureGacha,{keep:1});assert(saved.gacha.owned.includes('unknown-future-item'));assert(saved.gacha.owned.includes('hat-chef'));assert.equal(saved.gacha.avatar.top,'chef');assert.equal(saved.gacha.avatar.faceShape,1);assert.equal(saved.gacha.avatar.expression,5);assert.equal(saved.daily.progress,12);
const backup=await page.evaluate(()=>JSON.parse(localStorage.getItem(SushiAvatarStore.BACKUP)));assert.equal(backup.gems,802);assert.equal(backup.gacha.avatar.outfit,'chef');
await page.locator('.save-button').first().click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('コーデ 1'));
await page.locator('#reduceMotion').check();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('sushitan_login_bonus_v1')).avatarStudioV2?.settings?.reduced);await page.reload();assert.equal(await page.locator('[data-gender="male"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#faceShape').inputValue(),'1');assert.equal(await page.locator('#expression').inputValue(),'5');assert.equal(await page.locator('#reduceMotion').isChecked(),true);
// Gacha acquisition uses the same catalog, and keeps face/settings/looks/unrecognized fields.
await page.goto(origin+'/sushigacha/sushi-gacha.html');await page.waitForFunction(()=>typeof roll==='function');
assert.equal(await page.evaluate(()=>ITEMS.length),41);
const odds=await page.evaluate(()=>{const count={};for(const x of ITEMS)count[x.rarity]=(count[x.rarity]||0)+1;return count;});assert(odds.N&&odds.R&&odds.SR);assert.equal(odds.STARTER,3);
await page.evaluate(()=>{roll=()=>ITEMS.find(i=>i.id==='studio-wizard');return pull(false);});await page.locator('#skip').click();assert.equal(await page.locator('#prizeName').textContent(),'星のチュニック');
saved=await page.evaluate(KEY=>JSON.parse(localStorage.getItem(KEY)),KEY);assert.equal(saved.gems,752);assert.equal(saved.gacha.pulls,14);assert(saved.gacha.owned.includes('studio-wizard'));assert.equal(saved.gacha.avatar.expression,5);assert.equal(saved.avatarStudioV2.looks[0].faceShape,1);assert.deepEqual(saved.gacha.futureGacha,{keep:1});assert(saved.gacha.owned.includes('unknown-future-item'));
await page.locator('#equip').click();await page.waitForURL('**/sushi-avatar.html?item=studio-wizard');assert.equal(await page.locator('#equipLook').isEnabled(),true);await page.locator('#equipLook').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('sushitan_login_bonus_v1')).gacha.avatar.top==='studio-wizard');
await page.goto(origin+'/sushigacha/sushi-gacha.html');await page.evaluate(()=>{roll=()=>ITEMS.find(i=>i.id==='studio-wizard');return pull(false);});assert.equal(await page.evaluate(KEY=>JSON.parse(localStorage.getItem(KEY)).gems,KEY),732);await page.evaluate(()=>closeReveal());
// Reduced motion and live settings on a second page using the real home walker loader.
const home=await context.newPage();home.on('pageerror',e=>errors.push(e.message));await home.goto(origin+'/avatar-home-test.html');await home.waitForSelector('#homeAvatarWalker svg');assert.equal(await home.locator('#homeAvatarWalker svg').getAttribute('data-action'),'idle');assert.equal(await home.locator('[data-part="face"]').getAttribute('data-shape'),'1');await home.locator('.home-avatar-char').click();assert.equal(await home.locator('.home-avatar-menu').isVisible(),true);await home.locator('.home-avatar-menu button').click();
await page.goto(origin+'/sushigacha/sushi-avatar.html');await page.locator('#hideWalker').check();await home.waitForFunction(()=>document.getElementById('homeAvatarWalker').hidden);await page.locator('#hideWalker').uncheck();await page.locator('#reduceMotion').uncheck();await home.waitForFunction(()=>!document.getElementById('homeAvatarWalker').hidden&&document.querySelector('#homeAvatarWalker svg').dataset.action==='walk');
// 41 catalog items, 4 directions, 5 actions; 4 outlines and 6 expressions.
assert.equal(await page.evaluate(()=>{let n=0;for(const i of SushiAvatarV2.catalog)for(const direction of ['front','back','left','right'])for(const action of ['walk','idle','wave','sit','celebrate']){const svg=SushiAvatarV2.render({[i.slot]:i.id},{direction,action,time:.8});if(/NaN|undefined/.test(svg)||new DOMParser().parseFromString(svg,'image/svg+xml').querySelector('parsererror'))throw Error(i.id);n++;}return n;}),820);
for(const width of [390,320]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
if(process.env.AVATAR_SCREENSHOT_DIR){await page.setViewportSize({width:1360,height:1000});await page.screenshot({path:path.join(process.env.AVATAR_SCREENSHOT_DIR,'avatar-production-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(process.env.AVATAR_SCREENSHOT_DIR,'avatar-production-mobile.png'),fullPage:true});}
const widget=await context.newPage();widget.on('pageerror',e=>errors.push(e.message));await widget.goto(origin+'/avatar-widget-test.html');await widget.waitForSelector('#sushiAvatarWidget [data-part="face"]');assert.equal(await widget.locator('[data-part="face"]').getAttribute('data-shape'),'1');
// Corrupt storage must not be replaced by the editor or its setting controls.
await page.evaluate(KEY=>localStorage.setItem(KEY,'{broken'),KEY);await page.reload();await page.locator('#hideWalker').check();assert.equal(await page.evaluate(KEY=>localStorage.getItem(KEY),KEY),'{broken');assert.equal(await page.locator('#equipLook').isDisabled(),true);
assert.deepEqual(errors,[]);console.log('PASS: production migration, ownership, backup, current-ledger merge, face/save/settings, gacha acquisition/refund/equip, home/storage sync, widget renderer, 820 renders, 320/390px layouts, corrupt data protection');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
