const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),KEY='sushitan_login_bonus_v1',ID='reward-sushitan-aura';
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/home-test.html'){res.setHeader('Content-Type','text/html');return res.end('<body><script>window.__sushiSiteTaskbarLoaded=true;</script><script src="sushigacha/home-avatar-walker.js"></script>');}let f=path.resolve(root,'.'+u.pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(!fs.existsSync(f))f=path.resolve(root,'../rewards','.'+u.pathname);fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',path.extname(f)==='.html'?'text/html; charset=utf-8':path.extname(f)==='.js'?'application/javascript':'text/css');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});try{
const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('**/*',r=>{const url=r.request().url();if(url.includes('cdn.jsdelivr.net/npm/@supabase/'))return r.fulfill({contentType:'application/javascript',body:'window.supabase={createClient:()=>({rpc:async()=>({data:[],error:null})})};'});if(url.endsWith('/data/words_master_v2_reviewed.json'))return r.fulfill({json:[{en:'good',jp:'よい',synonyms:['nice'],antonyms:['bad']}]});return url.startsWith(origin)?r.continue():r.abort();});
await page.goto(origin+'/sushitan.html');await page.waitForFunction(()=>typeof GAME==='object');
const seed={gems:1234,extra:{keep:true},gacha:{version:4,owned:['starter','basic-bottom','studio-sneakers','reward-sushigiri','future-item'],pulls:12,avatar:{gender:'female',hand:'reward-sushigiri',aura:4,faceShape:1,expression:1,future:7}},avatarStudioV2:{looks:[{hand:'reward-sushigiri'}],settings:{reduced:true}}};
async function finish(score,level='all',clear=false,mode='core'){
await page.evaluate(async({score,level,clear,mode})=>{saveHighScore=async()=>{};loadRanking=async()=>{};GAME.running=true;GAME.reviewMode=false;GAME.score=score;GAME.maxCombo=0;GAME.timeLeft=0;GAME.usedQuestions=[];currentMode=mode;currentSushiLevel=level;await (clear?endPerfectClear():endGame());},{score,level,clear,mode});
}
for(const level of ['all','level1','level2','level3','level4']){
await page.evaluate(({KEY,seed})=>localStorage.setItem(KEY,JSON.stringify(seed)),{KEY,seed});
await page.evaluate(()=>localStorage.setItem('sushitan_total_score_v1','13499'));await finish(1500,level);assert.deepEqual(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY),seed);
await page.evaluate(()=>localStorage.setItem('sushitan_total_score_v1','13499'));await finish(1501,level);await page.waitForFunction(()=>JSON.parse(localStorage.getItem('sushitan_login_bonus_v1')).gacha.owned.includes('reward-sushitan-aura'));
assert.equal(await page.locator('#resultAvatarReward').getByRole('link',{name:'オーラを装備する'}).count(),1);
}
await page.evaluate(({KEY,seed})=>localStorage.setItem(KEY,JSON.stringify(seed)),{KEY,seed});await page.evaluate(()=>localStorage.setItem('sushitan_total_score_v1','13499'));await finish(1500,'level4',true);assert.deepEqual(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY),seed);await page.evaluate(()=>localStorage.setItem('sushitan_total_score_v1','13499'));await finish(1501,'level4',true);await page.getByText('限定オーラ「烈火のオーラ」を獲得しました！',{exact:true}).last().waitFor();
let saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);assert.equal(saved.gems,1234);assert.equal(saved.gacha.pulls,12);assert.deepEqual(saved.gacha.avatar,seed.gacha.avatar);assert.deepEqual(saved.avatarStudioV2,seed.avatarStudioV2);assert(saved.gacha.owned.includes('future-item'));
await page.evaluate(()=>Promise.all([SushiAvatarStore.awardGameResult('sushitan',15000),SushiAvatarStore.awardGameResult('sushitan',20000)]));assert.equal(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).gacha.owned.filter(x=>x==='reward-sushitan-aura').length,KEY),1);
await page.goto(origin+'/sushigacha/sushi-avatar.html?item='+ID);assert.equal(await page.locator('#aura').inputValue(),ID);await page.locator('#equipLook').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('sushitan_login_bonus_v1')).gacha.avatar.auraEffect==='reward-sushitan-aura');await page.reload();assert.equal(await page.locator('#aura').inputValue(),ID);assert.equal(await page.locator('#hero [data-item-art="reward-sushigiri"]').count(),1);assert.equal(await page.locator('#hero [data-item-art="reward-sushitan-aura"]').count(),1);
for(const width of [320,390]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
if(process.env.AVATAR_SCREENSHOT_DIR){await page.locator('#hero').screenshot({path:path.join(process.env.AVATAR_SCREENSHOT_DIR,'sushitan-aura-and-katana.png')});}
assert(await page.evaluate(()=>{for(const direction of ['front','back','left','right'])for(const action of ['walk','idle','wave','sit','celebrate']){const a={auraEffect:'reward-sushitan-aura',hand:'reward-sushigiri'};const svg=SushiAvatarV2.render(a,{direction,action,reduced:true,time:0});if(!svg.includes('data-item-art="reward-sushitan-aura"')||/NaN|undefined/.test(svg))return false;const x=new DOMParser().parseFromString(svg,'image/svg+xml');if(x.querySelector('parsererror'))return false;if(svg!==SushiAvatarV2.render(a,{direction,action,reduced:true,time:1}))return false;}return true;}));
const home=await context.newPage();await home.goto(origin+'/home-test.html');await home.waitForSelector('[data-item-art="reward-sushitan-aura"]');assert.equal(await home.locator('[data-item-art="reward-sushigiri"]').count(),1);
await page.locator('#aura').selectOption('0');assert.equal(await page.locator('#hero [data-item-art="reward-sushitan-aura"]').count(),0);await page.locator('#aura').selectOption(ID);await page.locator('[data-slot="auraEffect"]').click();assert.equal(await page.locator('[data-item="reward-sushitan-aura"]').count(),1);
await page.evaluate(({KEY,seed})=>localStorage.setItem(KEY,JSON.stringify(seed)),{KEY,seed});await page.goto(origin+'/sushigacha/sushi-avatar.html');assert.equal(await page.locator('#aura option[value="reward-sushitan-aura"]').count(),0);assert(await page.evaluate(async()=>{try{await SushiAvatarStore.equip({...SushiAvatarStore.load().avatar,auraEffect:'reward-sushitan-aura'});return false;}catch{return true;}}));
assert.equal(await page.evaluate(()=>SushiAvatarV2.item('reward-sushitan-aura').rarity),'REWARD');
assert.deepEqual(errors,[]);console.log('PASS: all five levels, 14999/15000 boundary, normal/perfect-clear results, duplicate protection, data preservation, sword+aura equip/reload/home, remove/re-equip, ownership, reduced motion, 320/390px');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
