'use strict';
const $=id=>document.getElementById(id),KEY='sukaishi_progress_v1';
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
let saved={correct:0,missed:[],best:{}};try{const v=JSON.parse(localStorage.getItem(KEY));if(v&&Array.isArray(v.missed))saved={...saved,...v};}catch{}
let era='all',queue=[],pos=0,points=0,correct=0,combo=0,missed=[],locked=false,order=[],review=false;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{}}
function screen(id){for(const s of ['homeScreen','gameScreen','resultScreen'])$(s).hidden=s!==id;window.scrollTo({top:0});}
function home(){screen('homeScreen');$('record').textContent=saved.correct;$('reviewHome').disabled=!saved.missed.length;$('reviewHome').textContent=saved.missed.length?`苦手 ${saved.missed.length} 問を復習 →`:'復習する問題はまだありません';}
const allEra={id:'all',name:'全時代ミックス',en:'ALL ERAS',icon:'🌏',range:'すべての時代から出題'};
for(const e of [...ERAS,allEra]){const b=document.createElement('button');b.className='era'+(e.id==='all'?' mix':'');b.innerHTML=`<span class="emoji">${e.icon}</span><span class="arrow">↗</span><strong>${e.name}</strong><span class="en">${e.en}</span><span class="range">${e.range}</span>`;b.onclick=()=>start(e.id);$('eras').append(b);}
function makeQueue(pool){const types=shuffle(['choice','truefalse','hint','match','order']);const groups=Object.fromEntries(types.map(t=>[t,shuffle(pool.filter(q=>q.type===t))]));let out=[];while(out.length<Math.min(10,pool.length)){let changed=false;for(const t of types){if(groups[t].length&&out.length<10){out.push(groups[t].pop());changed=true;}}if(!changed)break;}return out;}
function start(e,ids){era=e;review=!!ids;queue=makeQueue(QUESTIONS.filter(q=>(ids?ids.includes(q.id):(e==='all'||q.era===e))));if(!queue.length){home();return;}pos=points=correct=combo=0;missed=[];screen('gameScreen');render();}
const typeNames={choice:'🔎 一問一答',truefalse:'◯ 正誤判断',hint:'💡 ヒントクイズ',match:'↔ 組み合わせ',order:'⏳ 時系列'};
function button(text,fn){const b=document.createElement('button');b.className='answerBtn';b.textContent=text;b.onclick=fn;return b;}
function render(){const q=queue[pos];locked=false;order=[];$('answerArea').replaceChildren();$('feedback').hidden=true;$('feedback').className='feedback';$('submit').hidden=true;$('submit').disabled=true;$('next').hidden=true;$('translation').hidden=true;$('translate').setAttribute('aria-expanded','false');$('translate').textContent='日本語訳を見る';$('score').textContent=`${points} pt`;$('modeName').textContent=review?'苦手をもう一度':(ERAS.find(e=>e.id===era)||allEra).name;$('count').textContent=`QUESTION ${String(pos+1).padStart(2,'0')} / ${queue.length}`;$('progress').style.width=`${pos/queue.length*100}%`;$('combo').textContent=combo>1?`🔥 ${combo} COMBO`:'ゆっくり考えてOK';$('typeBadge').textContent=typeNames[q.type];$('eraBadge').textContent=ERAS.find(e=>e.id===q.era).name;
 $('prompt').textContent=q.type==='hint'?`Which answer fits these clues? ${q.hint}`:q.type==='truefalse'?`The event “${q.event}” took place in ${yearText(q.claimedYear)}.`:q.en;
 $('translation').textContent=q.type==='truefalse'?`「${q.eventJa}」が起きたのは${q.claimedYear<0?'紀元前'+(-q.claimedYear):'西暦'+q.claimedYear}年。正しい？`:q.type==='hint'?`ヒントに合う答えは？ ${q.hintJa}`:q.ja;
 $('help').textContent=q.type==='order'?'古い順に3つタップ。選び直すときは「やり直す」。':q.type==='match'?'3つの組を完成させて「決定」。同じ答えは1回ずつ。':q.type==='truefalse'?'BCE = 紀元前 / CE = 西暦。正しければ True。':'答えを1つ選ぼう。日本語訳を見ても減点されません。';
 if(['choice','hint','truefalse'].includes(q.type)){const box=document.createElement('div');box.className='options';const values=q.type==='truefalse'?['True / 正しい','False / 誤り']:shuffle(q.options);values.forEach((v,i)=>{const b=button(v,()=>{if(locked)return;const ok=q.type==='truefalse'?(i===0)===q.truth:v===q.answer;b.classList.add(ok?'correct':'wrong');finishAnswer(ok);[...box.children].forEach((x,j)=>{x.disabled=true;if(q.type==='truefalse'?(j===0)===q.truth:x.dataset.answer===q.answer)x.classList.add('correct');});});b.dataset.answer=v;box.append(b);});$('answerArea').append(box);}
 if(q.type==='order'){const slots=document.createElement('div');slots.className='orderSlots';slots.id='slots';$('answerArea').append(slots);const choices=document.createElement('div');choices.className='orderChoices';shuffle(q.members).forEach(f=>{const b=button(f.event,()=>{if(locked||order.includes(f.id))return;order.push(f.id);b.disabled=true;b.classList.add('selected');drawSlots(q);$('submit').disabled=order.length!==3;});b.dataset.eventId=f.id;choices.append(b);});$('answerArea').append(choices);const reset=button('↶ やり直す',()=>{order=[];drawSlots(q);choices.querySelectorAll('button').forEach(b=>{b.disabled=false;b.classList.remove('selected');});$('submit').disabled=true;});$('answerArea').append(reset);drawSlots(q);$('submit').hidden=false;}
 if(q.type==='match'){const opts=shuffle(q.members);q.members.forEach((f,i)=>{const row=document.createElement('label');row.className='matchRow';const text=document.createElement('span');text.textContent=f.en;if(!$('translation').hidden)text.textContent=f.ja;const select=document.createElement('select');select.setAttribute('aria-label',f.en);select.dataset.answer=f.id;const initial=document.createElement('option');initial.value='';initial.textContent='答えを選ぶ';select.append(initial);opts.forEach(o=>{const option=document.createElement('option');option.value=o.id;option.textContent=o.answer;select.append(option);});select.onchange=()=>{const values=[...$('answerArea').querySelectorAll('select')].map(x=>x.value);$('submit').disabled=values.some(v=>!v)||new Set(values).size!==3;};row.append(text,select);$('answerArea').append(row);});$('submit').hidden=false;}
 $('prompt').focus({preventScroll:true});}
function drawSlots(q){$('slots').replaceChildren();for(let i=0;i<3;i++){const s=document.createElement('div');s.className='slot';const f=q.members.find(f=>f.id===order[i]);s.textContent=`${i+1}. ${f?(f.event+(!$('translation').hidden?'（'+f.eventJa+'）':'')):'ここに選んだ出来事が入ります'}`;$('slots').append(s);}}
function finishAnswer(ok){if(locked)return;locked=true;const q=queue[pos];if(ok){combo++;correct++;points+=100+Math.min(50,(combo-1)*10);saved.correct++;saved.missed=saved.missed.filter(id=>id!==q.id);}else{combo=0;missed.push(q.id);saved.missed=[...new Set([...saved.missed,q.id])];}persist();$('score').textContent=`${points} pt`;$('progress').style.width=`${(pos+1)/queue.length*100}%`;$('feedback').hidden=false;$('feedback').classList.toggle('bad',!ok);const heading=document.createElement('strong');heading.textContent=ok?'✓ Correct / 正解':'Incorrect / 不正解';$('feedback').replaceChildren(heading);
 const add=(label,en,ja)=>{const block=document.createElement('section');block.className='explanation';const title=document.createElement('h3');title.textContent=label;const english=document.createElement('p');english.lang='en';english.textContent=en;const japanese=document.createElement('p');japanese.lang='ja';japanese.textContent=ja;block.append(title,english,japanese);$('feedback').append(block);};
 if(q.type==='order'){add('正しい順番',q.members.map(f=>yearText(f.year)+' — '+f.event).join('\n'),q.members.map(f=>(f.year<0?'紀元前'+(-f.year):'西暦'+f.year)+'年 — '+f.eventJa).join('\n'));q.members.forEach(f=>add(f.event+' / '+f.eventJa,f.noteEn,f.note));}
 else if(q.type==='match'){q.members.forEach(f=>add(f.answer+' / '+f.answerJa,f.en+'\n'+f.noteEn,f.ja+'\n'+f.note));}
 else {const answer=q.type==='truefalse'?(q.truth?'True / 正しい':'False / 誤り')+' — '+yearText(q.year):q.answer+' / '+q.answerJa;add(answer,q.noteEn,q.note);}
 $('answerArea').querySelectorAll('button,select').forEach(x=>x.disabled=true);$('submit').hidden=true;$('next').hidden=false;$('next').textContent=pos===queue.length-1?'結果を見る →':'次の問題へ →';$('feedback').classList.add('spark');}
function result(){screen('resultScreen');saved.best[era]=Math.max(saved.best[era]||0,points);persist();$('resultTitle').textContent=correct===queue.length?'全問正解！':'結果';$('resultText').textContent='';$('resultScore').textContent=points;$('resultCorrect').textContent=`${correct} / ${queue.length}`;$('resultNote').textContent=missed.length?`今回の ${missed.length} 問をもう一度。解説の記憶があるうちに！`:'すべての問題に正解しました。';$('reviewResult').hidden=!missed.length;}
 $('translate').onclick=()=>{const show=$('translation').hidden,q=queue[pos];$('translation').hidden=!show;$('translate').setAttribute('aria-expanded',String(show));$('translate').textContent=show?'日本語訳を閉じる':'日本語訳を見る';
 if(q.type==='match'){$('answerArea').querySelectorAll('.matchRow>span').forEach((s,i)=>s.textContent=show?q.members[i].en+'（'+q.members[i].ja+'）':q.members[i].en);$('answerArea').querySelectorAll('option').forEach(o=>{const f=q.members.find(f=>f.id===o.value);if(f)o.textContent=f.answer+(show?'（'+f.answerJa+'）':'');});}
 if(q.type==='order'){$('answerArea').querySelectorAll('[data-event-id]').forEach(b=>{const f=q.members.find(f=>f.id===b.dataset.eventId);b.textContent=f.event+(show?'（'+f.eventJa+'）':'');});drawSlots(q);}
 if(q.type==='choice'||q.type==='hint')$('answerArea').querySelectorAll('[data-answer]').forEach(b=>b.textContent=b.dataset.answer+(show?'（'+ANSWER_JA[b.dataset.answer]+'）':''));
 };
 $('submit').onclick=()=>{const q=queue[pos];if(locked||$('submit').disabled)return;finishAnswer(q.type==='order'?q.members.every((f,i)=>f.id===order[i]):[...$('answerArea').querySelectorAll('select')].every(s=>s.value===s.dataset.answer));};
 $('next').onclick=()=>{if(!locked)return;pos++;pos<queue.length?render():result();};$('quit').onclick=()=>{if(confirm('解答を終了して時代選択に戻りますか？ 解答済みの学習記録は残ります。'))home();};$('backHome').onclick=home;$('again').onclick=()=>start(era);$('reviewHome').onclick=()=>start('all',saved.missed);$('reviewResult').onclick=()=>start(era,[...missed]);home();
