/* Only the compact word/alias index is loaded, after search interaction. */
(()=>{'use strict';
const input=document.querySelector('#dictionary-query'),results=document.querySelector('#search-results'),status=document.querySelector('#search-status');
const normalize=s=>s.normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase();
const slug=s=>Array.from(s.toLowerCase(),c=>/[a-z0-9-]/.test(c)?c:'~'+c.codePointAt(0).toString(16)+'~').join('');
let indexPromise,sequence=0,timer;
function index(){return indexPromise ||= fetch('/dictionary/search-index.json').then(r=>{if(!r.ok)throw Error();return r.json();}).catch(e=>{indexPromise=null;throw e;});}
function distance(a,b){if(Math.abs(a.length-b.length)>2)return 3;let row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let next=[i];for(let j=1;j<=b.length;j++)next[j]=Math.min(next[j-1]+1,row[j]+1,row[j-1]+(a[i-1]!==b[j-1]));row=next;}return row[b.length];}
async function search(navigate=false){const ticket=++sequence,q=normalize(input.value);results.replaceChildren();if(!q){status.textContent='';return;}status.textContent='検索しています…';try{const rows=await index();if(ticket!==sequence)return;const exact=rows.find(([w])=>normalize(w)===q);if(navigate&&exact){location.href='/dictionary/'+slug(exact[0])+'/';return;}let found=rows.filter(([w,aliases])=>normalize(w).includes(q)||aliases.some(a=>normalize(a).includes(q)));found.sort((a,b)=>Number(normalize(b[0])===q)-Number(normalize(a[0])===q)||Number(normalize(b[0]).startsWith(q))-Number(normalize(a[0]).startsWith(q)));if(!found.length){found=rows.filter(([w])=>distance(q,normalize(w))<=2);status.textContent='この単語はまだすし辞書に収録されていません。スペルが近い単語：';}else status.textContent=found.length+'件の候補（最大20件を表示）';for(const [w] of found.slice(0,20)){const li=document.createElement('li'),a=document.createElement('a');a.textContent=w;a.href='/dictionary/'+slug(w)+'/';li.append(a);results.append(li);}if(!found.length)status.textContent+=' 候補がありません。';}catch{if(ticket===sequence)status.textContent='検索データを読み込めませんでした。通信を確認して再度検索してください。';}}
if(input){input.form.addEventListener('submit',e=>{e.preventDefault();clearTimeout(timer);search(true);});input.addEventListener('input',()=>{++sequence;clearTimeout(timer);timer=setTimeout(()=>search(),180);});const query=new URLSearchParams(location.search).get('q');if(query){input.value=query;search();}else if(document.querySelector('meta[name="robots"]')&&location.pathname.startsWith('/dictionary/')){input.value=location.pathname.split('/')[2].replace(/~([a-f0-9]+)~/g,(_,n)=>String.fromCodePoint(parseInt(n,16)));search();}}
const button=document.querySelector('#speak-word');if(button){button.addEventListener('click',()=>{const output=document.querySelector('#speech-status');if(!('speechSynthesis'in window)){output.textContent='この端末では読み上げを利用できません。';return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(document.querySelector('h1').textContent);u.lang='en-US';u.onerror=()=>output.textContent='音声を再生できませんでした。';speechSynthesis.speak(u);});}
})();
