(function (global) {
  'use strict';
  // Original example sentences. Coverage is deliberately explicit, not generated at runtime.
  const rows = [
    ['follow','Follow the instructions carefully.','指示に注意深く従ってください。','follow の直後に従う対象を置きます。follow to the instructions とはしません。'],
    ['consider','We are considering moving to a smaller house.','私たちはもっと小さな家へ引っ越すことを検討しています。','「〜することを検討する」は consider doing。consider to do と混同しないようにしましょう。'],
    ['increase','The number of visitors increased last year.','昨年、訪問者の数が増えました。','increase は「増える」と「増やす」の両方に使えます。この例では後ろに目的語がなく、「増える」です。'],
    ['expect','I expect the train to arrive soon.','電車はまもなく到着すると思います。','expect は予測や期待を表します。必ずしも「そうなってほしい」という願いではありません。expect A to do の形です。'],
    ['decide','We decided to walk home.','私たちは歩いて帰ることに決めました。','「〜することに決める」は decide to do。決定した内容を to の後ろに置きます。'],
    ['develop','She developed a new way to teach vocabulary.','彼女は語彙を教える新しい方法を開発しました。','この例は develop + 目的語で「〜を開発する」。Skills develop with practice. なら「技能が発達する」です。'],
    ['provide','The school provides students with lunch.','その学校は生徒に昼食を提供しています。','provide 人 with 物の形。provide lunch for students とも表せます。'],
    ['continue','The rain continued all night.','雨は一晩中降り続きました。','この例の continue は「続く」。continue studying のように、続ける行動を後ろに置くこともできます。'],
    ['include','The price includes breakfast.','料金には朝食が含まれています。','include は全体の中に何かを含むこと。朝食以外が含まれない、という意味ではありません。'],
    ['remain','Please remain calm.','落ち着いたままでいてください。','remain + 形容詞で「〜のままでいる」。この例の calm は動作ではなく状態を表します。'],
    ['reach','We reached the station before noon.','私たちは正午前に駅に着きました。','到着先は reach の直後に置きます。arrive at the station と違い、reach at the station とはしません。'],
    ['allow','My parents allow me to use their computer.','両親は私が両親のパソコンを使うことを許可しています。','allow 人 to do で「人が〜することを許す」。許可される人と行動を分けて読みます。'],
    ['force','The storm forced us to stay indoors.','嵐のため、私たちは屋内にとどまらざるを得ませんでした。','force 人 to do は「人に〜することを強いる」。人だけでなく状況も主語になります。'],
    ['offer','He offered to carry my bag.','彼は私のかばんを運ぼうかと申し出ました。','offer to do は自分から行動を申し出ること。相手に行動を求める ask とは区別します。'],
    ['realize','I realized that I had the wrong key.','私は違う鍵を持っていることに気づきました。','この例では、事実を理解して「気づく」。notice が見聞きして気づく場合に使われるのに対し、realize は理解に焦点があります。'],
    ['suggest','She suggested taking an earlier train.','彼女はもっと早い電車に乗ることを提案しました。','suggest doing で行動を提案します。この意味で suggest to take とはしません。'],
    ['require','This job requires patience.','この仕事には忍耐力が必要です。','require は必要条件を表します。単に「欲しい」を表す want と同じではありません。'],
    ['worry','Try not to worry about the test.','試験のことを心配しすぎないようにしてください。','心配の対象には worry about を使います。The news worried me. なら「その知らせが私を心配させた」です。'],
    ['wonder','I wonder why the shop is closed.','なぜその店が閉まっているのだろう。','wonder は「〜だろうかと思う」。why の後ろは the shop is の語順で、疑問文の is the shop にはしません。'],
    ['cost','This ticket costs 500 yen.','この切符は500円です。','費用がかかる物を主語にして cost + 金額。人を主語にする pay と区別しましょう。'],
    ["tend","I tend to forget names when I am nervous.","私は緊張していると名前を忘れがちです。","tend to do は『〜する傾向がある』。毎回必ずそうなる、という意味ではありません。to の後ろには動詞の原形を置きます。"],
    ["depend","The price depends on the size of the room.","料金は部屋の大きさによって決まります。","depend on は『〜次第である・〜に頼る』。この例は料金を決める条件を示しています。depend of とはしません。"],
    ["share","I share a kitchen with two other students.","私はほかの学生2人と台所を共用しています。","share 物 with 人で『物を人と共有する』。share は物を分配する場合にも使いますが、この例では同じ設備を一緒に使います。"],
    ["demand","The passengers demanded an explanation.","乗客たちは説明を要求しました。","demand は強く要求すること。ask for an explanation より強い表現です。丁寧な依頼で気軽に使うと強すぎる場合があります。"],
    ["support","My friends supported me during the competition.","友人たちは大会の間、私を支えてくれました。","support の直後に支える相手や支持する案を置きます。support me は金銭面の援助だけでなく、精神的に支える場合にも使えます。"],
    ["hire","The restaurant hired two new cooks.","そのレストランは新しい料理人を2人雇いました。","hire 人で『人を雇う』。人を募集する recruit と違い、この例では雇い入れることを表します。イギリス英語では車などを借りる意味もあります。"],
    ["regard","I regard this mistake as a chance to learn.","私はこの間違いを学ぶ機会だと考えています。","regard A as B で『AをBとみなす』。as を含めて覚えましょう。この例では mistake がA、a chance to learn がBです。"],
    ["base","The film is based on a true story.","その映画は実話に基づいています。","be based on は『〜に基づいている』。base A on B は『Aの基礎をBに置く』で、この例はその受け身です。"],
    ["improve","Reading aloud helped me improve my pronunciation.","音読は私が発音を改善するのに役立ちました。","improve は『〜を改善する』と『よくなる』の両方に使えます。My pronunciation improved. なら改善したもの自体が主語になります。"],
    ["recognize","I recognized her voice immediately.","私は彼女の声だとすぐに分かりました。","recognize は見聞きしたものが何か・誰かを識別する場合に使います。単に音が聞こえたという hear より、知っているものと結び付ける点が中心です。"],
    ["notice","I noticed a small crack in the window.","私は窓の小さなひびに気づきました。","notice は注意が向いて存在や変化に気づくこと。この例では目でひびを見つけています。考えて事実を理解する realize とは焦点が違います。"],
    ["suppose","I suppose the shop is still open.","その店はまだ開いていると思います。","I suppose ... は確信を少し控えて『〜だと思う』と言う表現。be supposed to do（〜することになっている）とは形と意味を区別しましょう。"],
    ["raise","Please raise your hand if you have a question.","質問があれば手を挙げてください。","raise はこの意味では目的語が必要です。raise your hand のように上げるものを示します。rise は The sun rises. のように、それ自体が上がるときに使います。"],
    ["prefer","I prefer tea to coffee.","私はコーヒーより紅茶が好きです。","prefer A to B で『BよりAを好む』。この比較では than ではなく to を使います。好みの対象が2つあるときは順番にも注意します。"],
    ["cheer","The crowd cheered the runners on.","観衆は走者たちに声援を送りました。","cheer 人 on は『人に声援を送る』。cheer 人 up は『人を元気づける』で、後ろの語によって意味が変わります。"],
    ["suffer","Many residents suffered from a lack of clean water.","多くの住民が清潔な水の不足に苦しみました。","suffer from は病気や問題に苦しむこと。suffer damage のように from を使わず『損害を受ける』と表す形もあります。"],
    ["describe","Can you describe the bag you lost?","なくしたかばんがどのようなものか説明できますか。","describe は特徴や様子を言葉で述べること。describe the bag to me のように、説明する相手には to を付けます。describe me the bag とは通常しません。"],
    ["prevent","The heavy snow prevented us from leaving.","大雪で私たちは出発できませんでした。","prevent 人 from doing で『人が〜するのを妨げる』。この例は出発を防いだ原因が主語です。from の後ろは leaving の形になります。"],
    ["reduce","We reduced the amount of paper we use.","私たちは使う紙の量を減らしました。","reduce は量・程度などを小さくすること。reduce by 20% は『20%分減らす』、reduce to 20% は『20%まで減らす』です。"],
    ["mistake","I mistook his silence for agreement.","私は彼の沈黙を同意だと勘違いしました。","動詞は mistake A for B（AをBと間違える）。過去形は mistook。名詞なら make a mistake（間違いをする）の形で使います。"],
    ["prepare","I prepared a short speech for the meeting.","私は会議のために短いスピーチを用意しました。","prepare a speech はスピーチ自体を用意すること。prepare for a meeting は会議に備えることです。for の有無で後ろの名詞との関係が変わります。"],
    ["encourage","Our teacher encouraged us to ask questions.","先生は私たちに質問するよう勧めてくれました。","encourage 人 to do は『人が〜するよう励ます・促す』。force と違い、無理にさせることを中心とする表現ではありません。"],
    ["prove","The task proved more difficult than we expected.","その作業は予想以上に難しいと分かりました。","prove + 形容詞は『〜だと分かる』。prove that ...（〜であると証明する）とは文の形が違います。この例では作業の難しさが明らかになっています。"],
    ["treat","Please treat the equipment with care.","機器を丁寧に扱ってください。","treat は『扱う』ほか『治療する』『おごる』などの意味があります。treat A as B は『AをBとして扱う』。文脈と後ろの語を確認しましょう。"],
    ["establish","They established a small company in 2018.","彼らは2018年に小さな会社を設立しました。","establish は組織・制度などを作り、成立させること。建物そのものを建てる build と区別します。establish a rule なら規則を定めることです。"],
    ["relate","These questions relate to the article we read.","これらの質問は私たちが読んだ記事に関係しています。","relate to は『〜に関係する』。relate A to B なら『AをBに関連付ける』です。目的語があるかどうかに注目します。"],
    ["compare","Compare your answer with the example.","自分の答えを例と比較してください。","compare A with B で両者の共通点や違いを比べます。compare A to B は比較にも使われ、何かにたとえる意味もあります。常に訳が一つに決まるわけではありません。"],
    ["spread","The news spread quickly through the town.","その知らせは町中にすぐに広まりました。","spread は『広がる』と『広げる』の両方に使えます。現在形・過去形・過去分詞がすべて spread なので、文脈から時を判断します。"],
    ["refer","The word they refers to the students in this sentence.","この文の they という語は、その生徒たちを指しています。","refer to は『〜を指す・〜に言及する・〜を参照する』。この例では代名詞の指す相手を説明しています。refer の後ろの to を忘れないようにします。"],
    ["supply","The farm supplies local shops with vegetables.","その農場は地元の店に野菜を供給しています。","supply A with B は『AにBを供給する』。supply vegetables to local shops のように、供給する物を先に置く形もあります。"],
    ["gain","She gained confidence through practice.","彼女は練習を通じて自信をつけました。","gain は努力や経験を通じて何かを得る場合に使います。gain confidence のほか gain experience（経験を積む）もよく使う組み合わせです。"],
    ["destroy","The fire destroyed the old warehouse.","火事で古い倉庫が破壊されました。","destroy は使えないほど破壊すること。damage は損傷を与えることで、完全に壊れているとは限りません。被害の程度に注意して使い分けます。"],
    ["apply","I applied for a part-time job at the library.","私は図書館のアルバイトに応募しました。","apply for は仕事・許可などに応募・申請する形。apply to は応募先を示したり、This rule applies to everyone. のように『当てはまる』を表したりします。"],
    ["seek","You should seek advice before signing the contract.","契約書に署名する前に助言を求めるべきです。","seek の直後に求めるものを置きます。seek advice に for は不要です。過去形・過去分詞は sought です。"],
    ["search","We searched the room for the missing key.","私たちはなくなった鍵を求めて部屋を捜しました。","search 場所 for 物で『場所を捜して物を探す』。search the room は捜す場所、search for the key は探している物を示します。"],
    ["claim","He claims that he saw a fox in the garden.","彼は庭でキツネを見たと主張しています。","claim は話し手が主張を紹介する語で、その内容が確認済みだとは限りません。claim that ... の内容と、裏付けがあるかを分けて読みます。"],
    ["draw","She drew the curtains to keep out the sunlight.","彼女は日差しを遮るためにカーテンを引きました。","draw は『描く』以外に『引く』の意味があります。draw the curtains は文脈によって開ける・閉めるの両方になり、この例は日差しを遮るので閉めています。"],
    ["refuse","He refused to answer the question.","彼はその質問に答えることを拒みました。","refuse to do は『〜することを拒む』。refuse an offer のように名詞も置けます。refuse answering より、この意味では refuse to answer を使います。"],
    ["respond","She responded to my message the next day.","彼女は翌日、私のメッセージに返答しました。","respond to は返答先や反応する対象を示します。answer my message には to が要らないので、動詞ごとの形に注意しましょう。"],
    ["mention","He mentioned the problem during lunch.","彼は昼食中にその問題に触れました。","mention の直後に話題を置きます。mention about the problem とは通常しません。詳しく説明する describe と違い、短く触れる場合にも使えます。"],
    ["judge","Do not judge a book by its cover.","本を表紙だけで判断してはいけません。","judge A by B は『Bを基準にAを判断する』。この表現は、人や物を外見だけで判断しないよう促すことわざとしても使われます。"],
    ["approach","We approached the entrance quietly.","私たちは静かに入り口に近づきました。","動詞 approach の直後に近づく対象を置き、approach to the entrance とはしません。名詞の an approach to learning では to を使えます。"],
    ["admit","He admitted making a mistake.","彼は間違えたことを認めました。","admit doing で『〜したことを認める』。admit that he had made a mistake とも言えます。入場を認める意味もあるので文脈を確認します。"],
    ["reflect","The lake reflected the mountains.","湖は山々を映していました。","この例は光や像を『反射する・映す』意味。reflect on an experience は『経験を振り返って考える』で、on を伴う別の使い方です。"],
    ["perform","The technician performed a safety check.","技術者は安全点検を行いました。","perform a check は点検を実施すること。perform は演奏や演技にも使われますが、後ろが task や check なら作業の実行を表します。"],
    ["bore","The long speech bored the audience.","長いスピーチに聴衆は退屈しました。","bore 人で『人を退屈させる』。退屈させるものは boring、退屈した人の気持ちは bored。I am boring. と I am bored. は意味が違います。"],
    ["survive","Several trees survived the storm.","何本かの木は嵐を生き延びました。","survive the storm のように、切り抜けた出来事を直接置けます。survive from the storm とは通常しません。目的語なしでも『生き残る』と表せます。"],
    ["represent","The blue line represents the average temperature.","青い線は平均気温を表しています。","represent は図や記号が何かを『表す』場合に使えます。represent a country なら国を『代表する』意味になります。"],
    ["argue","They argued that the park should remain open.","彼らは公園を開放したままにすべきだと主張しました。","argue that ... は理由を示して主張すること。argue with 人 about 事柄なら『人と事柄について口論する』場合もあり、必ずけんかの意味ではありません。"],
    ["grant","The council granted them permission to use the hall.","評議会は彼らにホールの使用許可を与えました。","grant 人 物で許可や権利などを正式に与えます。この例の permission to use は『使用する許可』というまとまりです。"],
    ["indicate","The arrow indicates the direction of the exit.","矢印は出口の方向を示しています。","indicate は記号や情報が何かを示すこと。示唆する意味の場合もあり、The results indicate ... だけで絶対的な証明を意味するわけではありません。"],
    ["belong","This umbrella belongs to my sister.","この傘は私の姉のものです。","belong to は所有者や所属先を示します。通常、この所有の意味で is belonging や is belonged とはしません。"],
    ["acquire","He acquired useful skills through volunteer work.","彼はボランティア活動を通じて役立つ技能を身につけました。","acquire skills は学習や経験を通じて技能を習得すること。物や権利を取得する意味にも使われ、対象によって訳が変わります。"],
    ["reply","Please reply to this email by Friday.","金曜日までにこのメールに返信してください。","reply to は返答する対象を示します。reply は答えを返す意味が中心で、respond は刺激への反応など、言葉以外にも使えます。"],
    ["feed","Please do not feed the birds.","鳥に餌を与えないでください。","feed の直後に食べ物を与える相手を置けます。feed the birds bread なら相手と食べ物の両方を示します。過去形・過去分詞は fed です。"],
    ["escape","The cat escaped from the cage.","猫はかごから逃げ出しました。","escape from は逃げ出した場所を示します。escape danger（危険を免れる）のように、避けたものを直接置く使い方もあります。"],
    ["replace","We replaced the old printer with a new one.","私たちは古いプリンターを新しいものに取り替えました。","replace A with B は『AをBに取り替える』。取り除かれるのはA、代わりに入るのはBです。順番を逆にしないようにしましょう。"],
    ["reveal","The test revealed a small error in the program.","テストでプログラムの小さな誤りが明らかになりました。","reveal は隠れていたことや未知だったことを明らかにする語。この例ではテストが誤りを作ったのではなく、存在を明らかにしています。"],
    ["surround","Tall trees surround the house.","高い木々がその家を取り囲んでいます。","surround A は『Aを取り囲む』。家を主語にすると The house is surrounded by tall trees. という受け身になります。"],
    ["suit","Friday afternoon suits me best.","金曜日の午後が私には一番都合がよいです。","suit は好みや都合に合うこと。服なら suit は似合う、fit はサイズが合う、match は色などが調和するという違いがあります。"],
    ["estimate","We estimate that the repair will take two days.","私たちは修理に2日かかると見積もっています。","estimate は情報を基におおよそを見積もること。正確に測った値とは限りません。estimate the cost なら費用を見積もります。"],
    ["aim","We aim to finish the project by June.","私たちは6月までにその計画を終えることを目指しています。","aim to do は『〜することを目指す』。aim at a target は『標的を狙う』で、後ろの形によって目標の示し方が変わります。"],
    ["earn","She earns money by teaching piano.","彼女はピアノを教えてお金を稼いでいます。","earn は仕事や努力により得ること。earn respect（尊敬を得る）のようにお金以外にも使えます。単に受け取る receive とは焦点が違います。"],
    ["decline","The number of customers declined in winter.","冬には客の数が減りました。","この例の decline は『減少する』。decline an invitation は『招待を辞退する』です。主語や目的語を見て意味を判断します。"],
    ["afford","We cannot afford to buy a new car this year.","私たちは今年、新車を買う余裕がありません。","can afford to do は『〜する余裕がある』。金銭だけでなく時間や損失に耐える余裕にも使えます。afford buying ではなく to buy の形です。"],
    ["confuse","I sometimes confuse these two words.","私はときどきこの2つの単語を混同します。","confuse A with B で『AとBを混同する』とも言えます。confused は混乱した気持ち、confusing は混乱させる性質を表します。"],
    ["graduate","She graduated from university last spring.","彼女は昨年の春、大学を卒業しました。","卒業した学校を示す基本形は graduate from。アメリカ英語では from を省く用法もありますが、学習では from を含む形を覚えると使いやすいです。"],
    ["vary","Opening hours vary from store to store.","営業時間は店によって異なります。","vary from A to A は『Aごとに異なる』。vary は違いや変動を表し、必ず増える・必ず減るという方向は示しません。"],
    ["remove","Please remove your shoes before entering.","入る前に靴を脱いでください。","remove はその場所から取り除くこと。remove the stain from the shirt なら『シャツから染みを落とす』です。必ず破壊する意味ではありません。"],
    ["insist","He insisted on paying for lunch.","彼は昼食代を払うと言って譲りませんでした。","insist on doing は『〜すると言って譲らない』。on の後ろは動名詞です。insist that ... という文を続ける形もあります。"],
    ["examine","The mechanic examined the engine carefully.","整備士はエンジンを注意深く調べました。","examine は状態を知るために詳しく調べること。単に見る look at よりも、点検・検査する目的がはっきりしています。"],
    ["remind","Please remind me to bring my notebook.","ノートを持ってくるよう、私に念を押してください。","remind 人 to do は『人に〜することを思い出させる』。remind 人 of 物は物事を思い出させる形。remember は本人が思い出すことです。"],
    ["contribute","Regular exercise contributes to good health.","定期的な運動は健康に役立ちます。","contribute to は『〜に貢献する・〜の一因となる』。to は前置詞なので、動作を続けるなら doing の形。悪い結果の一因を示す場合にも使います。"],
    ["warn","They warned us about the icy road.","彼らは道路が凍結していることについて私たちに注意を促しました。","warn 人 about 危険で『危険について人に警告する』。warn 人 not to do なら、危険な行動をしないよう警告します。"],
    ["connect","This bridge connects the island to the mainland.","この橋は島と本土をつないでいます。","connect A to B は『AをBにつなぐ』。connect A with B も使われます。名詞 connection と合わせて、つながりの意味を確認しましょう。"],
    ["match","Your scarf matches your coat.","あなたのマフラーはコートによく合っています。","match はこの例では色や柄などが調和すること。match your coat と直接目的語を置けます。match the record なら記録に並ぶ意味になります。"],
    ["focus","Let us focus on one problem at a time.","一度に1つの問題に集中しましょう。","focus on は『〜に集中する』。focus your attention on ... のように、何を集中させるかを目的語で示す形もあります。"],
    ["reject","The committee rejected the proposal.","委員会はその提案を却下しました。","reject は提案や申請などを受け入れないこと。refuse to do は行動することを拒む形ですが、この意味で reject to do とはしません。"],
    ["convince","The evidence convinced me that she was right.","その証拠によって、私は彼女が正しいと確信しました。","convince 人 that ... は『人に〜だと確信させる』。convince 人 of 名詞という形もあります。この例は証拠を基に考えが変わっています。"],
    ["associate","I associate this song with my school days.","私はこの歌を聞くと学生時代を連想します。","associate A with B は『AをBと結び付けて考える』。be associated with は『〜と関連がある』ですが、関連だけで因果関係があるとは限りません。"],
    ['available','This room is available tomorrow.','この部屋は明日利用できます。','available は物や人が「利用できる・対応できる」こと。possible は物事が「実現可能」であることです。部屋の空きを表すこの例では available を使います。']
  ];
  const notes = new Map(rows.map(([word,example,translation,note])=>[word,{word,example,translation,note}]));
  const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function get(word) { return notes.get(String(word || '').normalize('NFKC').trim().toLowerCase()) || null; }
  function html(word) {
    const entry=get(word);
    if (!entry) return '<p class="word-note">この単語の例文・用法解説は未掲載です。まず表示された意味を確認し、苦手復習でもう一度思い出してみましょう。</p>';
    return `<details class="word-note"><summary>${escape(entry.word)} の例文・使い方</summary><p lang="en">${escape(entry.example)}</p><p>${escape(entry.translation)}</p><p>${escape(entry.note)}</p><details><summary>確認練習：例文を隠して、日本語から英語で言ってみる</summary><p lang="en">${escape(entry.example)}</p><p>答えを見ずに言えたか確認し、後で苦手復習にも取り組みましょう。この確認だけでは学習記録は変わりません。</p></details></details>`;
  }
  global.SushiWordNotes=Object.freeze({get,html,entries:()=>rows.map(([word])=>({...get(word)}))});
})(window);
